---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: 叢集是SolidFire 一套由節點集合所組成的不同步儲存系統中樞。叢集中必須至少有四個節點、SolidFire 才能實現不必要的儲存效率。叢集會以單一邏輯群組的形式出現在網路上、然後可作為區塊儲存設備進行存取。 
---
= 叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
叢集是SolidFire 一套由節點集合所組成的不同步儲存系統中樞。叢集中必須至少有四個節點、SolidFire 才能實現不必要的儲存效率。叢集會以單一邏輯群組的形式出現在網路上、然後可作為區塊儲存設備進行存取。

建立新叢集時、會將節點初始化為叢集的通訊擁有者、並為叢集中的每個節點建立網路通訊。此程序僅會針對每個新叢集執行一次。您可以使用元素UI或API建立叢集。

您可以新增其他節點來橫向擴充叢集。新增節點時、不會中斷服務、而且叢集會自動使用新節點的效能和容量。

系統管理員和主機可以使用虛擬IP位址來存取叢集。叢集中的任何節點都可以裝載虛擬IP位址。管理虛擬IP（MVIP）可透過1GbE連線來進行叢集管理、而儲存虛擬IP（SVIP）則可透過10GbE連線、讓主機存取儲存設備。無論SolidFire 什麼規模或組成的叢集、這些虛擬IP位址都能實現一致的連線。如果託管虛擬IP位址的節點故障、叢集中的另一個節點就會開始託管虛擬IP位址。


NOTE: 從Element 11.0版開始、節點可設定為使用IPv4、IPv6或兩者的管理網路位址。這適用於儲存節點和管理節點、但不支援IPv6的管理節點11.3及更新版本除外。建立叢集時、MVIP只能使用單一的IPv4或IPv6位址、而且必須在所有節點上設定對應的位址類型。

.叢集的詳細資訊
* <<Authoritative storage clusters>>
* <<Rule of thirds>>
* <<Stranded capacity>>
* <<Storage efficiency>>
* <<Storage cluster quorum>>




== 驗證儲存叢集

權威儲存叢集是NetApp混合雲控制系統用來驗證使用者的儲存叢集。

如果您的管理節點只有一個儲存叢集、則它是授權叢集。如果您的管理節點有兩個以上的儲存叢集、其中一個叢集會指派為授權叢集、而且只有該叢集的使用者才能登入NetApp混合雲控制。若要瞭解哪個叢集是授權叢集、您可以使用「Get /mnode/about」API。回應時、「toke_URL」欄位中的IP位址是驗證儲存叢集的管理虛擬IP位址（MVIP）。如果您嘗試以非授權叢集的使用者身分登入NetApp混合雲控制、登入嘗試將會失敗。

許多NetApp混合雲控制功能都是專為搭配多個儲存叢集使用而設計、但驗證和授權卻有其限制。驗證與授權的限制在於、授權叢集的使用者可以在其他綁定至NetApp混合雲控制的叢集上執行動作、即使他們不是其他儲存叢集的使用者。在繼續管理多個儲存叢集之前、您應確保在授權叢集上定義的使用者已在所有其他具有相同權限的儲存叢集上定義。

在繼續管理多個儲存叢集之前、您應確保在授權叢集上定義的使用者已在所有其他具有相同權限的儲存叢集上定義。您可以從管理使用者 link:../storage/concept_system_manage_manage_cluster_administrator_users.html["Element軟體使用者介面"]。

請參閱 link:../mnode/task_mnode_manage_storage_cluster_assets.html["建立及管理儲存叢集資產"] 以取得有關使用管理節點儲存叢集資產的詳細資訊。



== 三分之一規則

當您在NetApp SolidFire 支援資源集區中混合使用儲存節點類型時、任何單一儲存節點都無法容納超過33%的儲存叢集總容量。



== 閒置容量

如果新增的節點佔叢集總容量的50%以上、則此節點的部分容量將無法使用（「閒置」）、因此符合容量規則。在新增更多儲存容量之前、情況仍會如此。如果新增的大型節點也不遵守容量規則、則先前閒置的節點將不再處於閒置狀態、而新新增的節點則會陷入閒置狀態。容量應一律成對新增、以免發生這種情況。當節點變成閒置狀態時、會拋出適當的叢集故障。



== 儲存效率

NetApp SolidFire 支援的儲存叢集利用重複資料刪除、壓縮及精簡配置、減少儲存磁碟區所需的實體儲存容量。

* *壓縮*
+
壓縮可將資料區塊合併到壓縮群組中、以減少磁碟區所需的實體儲存容量、每個資料區塊都儲存為單一區塊。

* *重複資料刪除*
+
重複資料刪除技術可捨棄重複的資料區塊、減少磁碟區所需的實體儲存容量。

* *精簡配置*
+
精簡配置的磁碟區或LUN並非預先保留儲存設備。而是根據需要動態分配儲存設備。刪除磁碟區或LUN中的資料時、可用空間會釋出回儲存系統





== 儲存叢集仲裁

Element軟體會從所選節點建立儲存叢集、以維護叢集組態的複寫資料庫。參加叢集集合至少需要三個節點、以維持叢集恢復能力的仲裁。
