---
permalink: concepts/concept_solidfire_concepts_nodes.html 
sidebar: sidebar 
keywords: what is, node, management node, storage node, fibre channel, state, pending, active 
summary: 節點是群組為叢集的硬體、可作為區塊儲存或運算資源來存取。 
---
= 節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
節點是一種硬體或虛擬資源、可群組為叢集、以提供區塊儲存和運算功能。

此軟體可定義叢集的各種節點角色。NetApp Element節點角色類型如下：

*  node
*  node
*  Channel node


 states of operation,節點狀態 視叢集關聯而定。



== 管理節點

管理節點是一部虛擬機器、用於升級及提供系統服務、包括監控與遙測、管理叢集資產與設定、執行系統測試與公用程式、以及啟用NetApp支援存取來進行疑難排解。link:../concepts/concept_intro_management_node.html["深入瞭解"]



== 儲存節點

這個伺服器包含一系列的磁碟機、這些磁碟機透過Bond10G網路介面彼此通訊。SolidFire節點中的磁碟機包含區塊和中繼資料空間、可用於資料儲存和資料管理。每個節點都包含NetApp Element 一個原廠的Imagesoftware映像。

儲存節點具有下列特性：

* 每個節點都有唯一的名稱。如果系統管理員未指定節點名稱、則預設為SF-XXXX、其中XXXX為系統產生的四個隨機字元。
* 每個節點都有自己的高效能非揮發性隨機存取記憶體（NVRAM）寫入快取、可改善整體系統效能並縮短寫入延遲。
* 每個節點都連接至兩個網路（儲存與管理）、每個網路都有兩個獨立的連結來提供備援與效能。每個節點都需要每個網路上的IP位址。
* 您可以建立具有新儲存節點的叢集、或是將儲存節點新增至現有叢集、以增加儲存容量和效能。
* 您可以隨時從叢集新增或移除節點、而不中斷服務。




== Fibre Channel節點

供應連接至光纖通道交換器的鏈路、您可以連接至光纖通道用戶端。SolidFireFibre Channel節點可做為光纖通道和iSCSI傳輸協定之間的傳輸協定轉換器、讓您將Fibre Channel連線功能新增至任何新SolidFire 的或現有的叢集。

Fibre Channel節點具有下列特性：

* Fibre Channel交換器可管理光纖的狀態、提供最佳化的互連。
* 兩個連接埠之間的流量只會流經交換器、不會傳輸到任何其他連接埠。
* 連接埠故障已隔離、不會影響其他連接埠的運作。
* 多對連接埠可在網路中同時通訊。




== 節點作業狀態

[role="lead"]
視組態層級而定、節點可能處於多種狀態之一。

* *可用*
+
該節點沒有相關聯的叢集名稱、而且尚未成為叢集的一部分。

* *待處理*
+
節點已設定完成、可新增至指定的叢集。

+
存取節點不需要驗證。

* *擱置中的Active*
+
系統正在節點上安裝相容的Element軟體。完成後、節點會移至「作用中」狀態。

* *主動*
+
節點正在參與叢集。

+
需要驗證才能修改節點。



在這些狀態中、有些欄位是唯讀的。

[discrete]
== 如需詳細資訊、請參閱

* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

