---
permalink: concepts/concept_rn_whats_new_element.html 
sidebar: sidebar 
keywords: netapp, solidfire, element, storage, solidfire enterprise sds 
summary: NetApp會定期更新SolidFire 支援功能和元件軟體、為您帶來新功能、增強功能和錯誤修復。 
---
= Element 軟體的新功能
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp會定期更新SolidFire 支援功能和元件軟體、為您帶來新功能、增強功能和錯誤修復。Element 12.8是最新版本、包含安全性與系統元件更新、作業改善及已解決的問題。


NOTE: 根據儲存叢集上目前執行的元素版本、會將累積式軟體和韌體更新安裝為Element 12.8升級的一部分。例如，如果叢集目前正在執行 Element 12.5 ，您可以直接升級至 Element 12.8 ，從 Element 12.7 和 12.8 取得累積更新。有關支持的升級路徑，請參閱知識庫文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software["執行 NetApp Element 軟體之儲存叢集的升級對照表為何"^]。



== 元件12.8

深入瞭解 Element 12.8 的新功能。



=== Volume 負載平衡

元素 12.8 介紹 Volume Load Balancing 功能。您可以使用此功能，根據每個磁碟區的實際 IOPS 層級來平衡節點之間的磁碟區，而非 QoS 原則中設定的最低 IOPS 。您只能使用 Volume Load Balancing 功能來平衡磁碟區。您無法使用它來平衡虛擬磁碟區。Volume Load Balancing 功能預設為停用。您可以使用 API 參數搭配link:../api/reference_element_api_enablefeature.html["啟用功能"]和 link:../api/reference_element_api_disablefeature.html["DisableFeature"] API 方法，或使用link:../storage/task_system_manage_cluster_volume_load_balancing.html["Volume 負載平衡"]元素 UI 中的選項來啟用和停用它 `VolumeLoadBalanceOnActualIOPS`。



=== 檢視節點使用率資訊

有了 Element 12.8 ，您就可以像使用 `GetNodeStats`和 `ListNodeStats` API 方法一樣檢視節點使用率資訊 `nodeHeat`。 `nodeHeat`物件是物件的成員 `nodeStats`，會根據主要 IOPS 或整體 IOPS 與一段時間內平均的已設定 IOPS 比率，顯示節點使用率資訊。

此外，您可以在元素 UI 中的節點「檢視詳細資料」顯示中，以百分比檢視節點使用率 `recentPrimaryTotalHeat`。



=== 檢視磁碟區的 I/O 統計資料

有了 Element 12.8 ，您可以使用 `GetVolumeStats`和 `ListVolumeStatsByVolume` API 方法，檢視磁碟區的 I/O 使用統計資料 `sliceIopsStats`。I/O 統計資料是使用磁碟區的讀取和寫入 IOPS 資訊來計算，並在過去 24 小時和最後一小時的兩個期間內進行測量。link:../api/reference_element_api_volumestats.html#object-members["深入瞭解"]。



=== iSCSI 工作階段的 CHAP 演算法

當主機 iSCSI 啟動器建立具有元素 iSCSI 目標的 iSCSI 工作階段時，會要求使用挑戰握手驗證傳輸協定（ CHAP ）演算法清單。從元素 12.8 開始，您可以檢視元素 iSCSI 目標選擇用於 iSCSI 工作階段的支援 CHAP 演算法。



=== 升級 VM 硬體版本

如果您正在執行現有管理節點的就地升級至元素 12.8 ，則在升級之前，必須確保管理節點上的 VM 硬體版本與 ESXi 6.7 （ VM 硬體版本 14 ）或更新版本相容，視您的環境而定。link:../upgrade/task_hcc_upgrade_management_node.html#step-1-upgrade-vm-hardware-version-on-a-management-node["深入瞭解"]。



== 元素12.7

深入瞭解 Element 12.7 的新功能。



=== 安全的CHAP演算法

Element 12.7支援安全的FIPS相容挑戰握手驗證傳輸協定（CHAP）演算法SHA1、SHA-256和SHA3-256。 link:../storage/task_data_manage_accounts_work_with_accounts_task.html["深入瞭解"]。



=== 動態區塊（Bin）同步處理速度

叢集作業（例如新增、升級或維護節點、或新增磁碟機等）會觸發區塊（bin）同步、將區塊資料分散到叢集配置中的新節點或更新節點。使用單一慢速做為預設的同步處理速度、會導致這些作業耗費很長時間、而且不會利用較大節點的較高處理能力。從元素12.7開始、同步處理速度會根據儲存節點上的核心數量動態調整、讓這些作業能夠大幅加快執行速度。

例如、當您在現有叢集新增執行元素12．7的大型28核心儲存節點（H610S、SF19210和SF38410）時、資料的同步輸入速率會自動調至110 Mbps、而非60 Mbps。此外、當您將這些大型儲存節點從節點維護模式中移出時、例如使用NetApp混合雲控制將元素12.3.x或更新版本升級至元素12.7時、變更區塊資料速率的同步輸入速率會自動調至110Mbps、而非20Mbps。

當您將中型16核心儲存節點（H410S）和小型12核心儲存節點（SF4805）新增至元素12.7叢集時、資料的同步輸入速率仍維持在60Mbps； 但是、當您將變更的區塊從元素12.3.x升級至元素12.7時、如果將它們從節點維護模式中移出、則同步處理速度會自動從中型儲存節點的20Mbps調至60Mbps、而較小儲存節點的速度則為40Mbps。

當您移除儲存節點時、不會影響區塊同步輸出速度、進而避免對用戶端I/O造成效能影響



=== 垃圾回收改善

對於具有較大儲存節點的叢集、例如使用1PB空間的H610S-4、會以覆寫功能執行非常高的工作負載、 而且重複資料刪除和壓縮率很高、現在垃圾回收作業可以跟上預設的開放式篩選器大小、因為較大的節點已從700GB或更大的記憶體增加到1048576位元。此變更會在您將儲存節點升級至元素12.7之後自動生效、而且不會對較小的節點造成任何影響。



=== 擴充性改善

有了Element 12.7、您不再需要依照特定的順序、將多個儲存節點加入現有叢集、而這些儲存節點的區塊和中繼資料磁碟機值也很大。使用Element UI或API、您只需選取所有可用的磁碟機、然後同時大量新增磁碟機即可。Element 12.7會自動管理資料同步、以便同時同步所有區塊服務。當每個節點的區塊服務完成同步時、該節點上的中繼資料磁碟機便可指派給主機磁碟區。這項擴充性改善可大幅縮短讀取回應延遲、並可在新增儲存節點之間同步資料時、避免效能降低。



=== 儲存節點韌體更新

Element 12.7內含儲存韌體套裝軟體2.164.0版、其中包含對新系統元件的支援。 link:https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.164.0.html["深入瞭解"]。


NOTE: Element 12.7版本中沒有新的韌體更新。不過、根據儲存節點上目前執行的韌體套裝組合、當您升級至Element 12.7時、就會安裝累積性更新。



=== 本文檔SolidFire Active IQ

在這個功能表中SolidFire Active IQ 、您現在可以瀏覽至「QoS管理」頁面、檢視叢集的建議和節點節流資訊。此外、叢集儀表板現在會顯示快照總數。其他近期的增強功能包括新增作用中磁碟區的主要和次要節點資訊、以及節點上主要磁碟區的平均處理量、IOPS和過去30分鐘的平均延遲。

您現在可以從SolidFire Active IQ Element軟體文件中存取《支援》文件。 link:https://docs.netapp.com/us-en/element-software/monitor-storage-active-iq.html["深入瞭解"]。



=== NetApp線上錯誤包含已解決且已知的問題

NetApp錯誤線上工具中已列出已解決及已知的問題。您可以瀏覽這些問題、以取得Element軟體和其他產品、網址為 https://mysupport.netapp.com/site/products/all/details/element-software/bugsonline-tab["NetApp線上錯誤"^]。



== 要點12.5

深入瞭解 Element 12.5 的新功能。



=== 改善儲存節點存取

Element 12.5使用簽署的SSH憑證、改善個別節點的遠端存取。為了提供對儲存節點的安全遠端存取、在儲存節點的RTFI期間、現在會建立一個名為「sfreadonly」的有限權限本機使用者帳戶。「sfreadonly」帳戶可存取儲存節點後端、以進行基本維護或疑難排解。您現在可以為叢集管理員使用者設定「最大管理」存取類型、以便NetApp支援視需要存取叢集。



=== 增強的自訂保護網域管理功能

Element 12.5具備新的使用者介面、可讓您快速輕鬆地檢視現有的自訂保護網域、並設定新的自訂保護網域。



=== 新增及改善的叢集故障、事件和警示

Element 12.5採用新的叢集故障代碼「BmcselfTestFailed」和「CpuThermalEventThreshold」、可增強系統疑難排解的能力。元素12.5也包含現有叢集事件和警示的健全性改善、例如「節點離線」、「Volume離線」、「driveHealthFault」、「網路事件」、 和「cSumEvent」。



=== 從Create Cluster UI啟用靜止軟體加密

在建立叢集UI中新增核取方塊後、元素12.5可讓您在SolidFire 建立叢集期間、針對整個叢集的All Flash儲存叢集啟用全叢集軟體加密功能。



=== 儲存節點韌體更新

Element 12.5包含儲存節點的韌體更新。 link:../concepts/concept_rn_relatedrn_element.html#storage-firmware["深入瞭解"]。



=== 增強安全性

元素12.5包含的緩和措施可關閉元素軟體曝險於Apache log4j弱點。啟用虛擬Volume（VVols）功能的NetApp SolidFire 支援區儲存叢集、會暴露於Apache log4j弱點。如需NetApp Element 有關解決方案的資訊、請參閱｛url-peak｝[KB文章]。

如果您執行的是Element 11.x、12.0或12.2、或是儲存叢集已在元素123或12.3.1、且已啟用VVols功能、則應升級至12.5。

元素12.5也包含120多項可修復的CVE安全性弱點。



== 如需詳細資訊、請參閱

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["NetApp混合雲控制與管理服務版本說明"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]
* http://docs.netapp.com/sfe-122/index.jsp["適用於舊版的VMware及Element軟體文件中心SolidFire"^]
* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* link:../hardware/fw_storage_nodes.html["支援的儲存韌體版本SolidFire 、適用於不支援的儲存節點"]

