---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: 執行Element軟體的叢集會產生叢集故障、以在叢集的容量不足時警告儲存管理員。叢集完整度分為三個層級、所有層級都顯示在NetApp Element 這個畫面上：警告、錯誤和嚴重。 
---
= 瞭解叢集完整度層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
執行Element軟體的叢集會產生叢集故障、以在叢集的容量不足時警告儲存管理員。叢集完整度分為三個層級、所有層級都顯示在NetApp Element 這個畫面上：警告、錯誤和嚴重。

系統使用BlockClusterFull錯誤代碼來警告叢集區塊儲存設備是否完整。您可以從元素UI的警示索引標籤檢視叢集完整嚴重性層級。

下列清單包含有關BlockClusterFull嚴重性等級的資訊：

* *警告*
+
這是客戶可設定的警告、會在叢集的區塊容量接近錯誤嚴重性層級時顯示。根據預設、此層級在錯誤層級下設為3%、可透過元素UI和API進行調整。您必須新增更多容量、或盡快釋出容量。

* *錯誤*
+
當叢集處於這種狀態時、如果節點遺失、叢集中的容量將不足以重建兩倍Helix資料保護。當叢集處於這種狀態時、新的Volume建立、複製和快照都會遭到封鎖。對於任何要進入的叢集而言、這不是安全或建議的狀態。您必須新增更多容量、或立即釋出容量。

* *重大*
+
發生此重大錯誤的原因是叢集已耗用100%。它處於唯讀狀態、無法對叢集建立新的iSCSI連線。達到此階段時、您必須立即釋出或新增更多容量。



系統會使用Metadata ClusterFull錯誤代碼來警告叢集中繼資料儲存設備的完整度。您可以從元素UI中「報告」索引標籤的「總覽」頁面上的「叢集容量」區段、檢視叢集中繼資料儲存設備的完整度。

下列清單包含有關Metadata ClusterFull嚴重性等級的資訊：

* *警告*
+
這是客戶可設定的警告、會在叢集的中繼資料容量接近錯誤嚴重性層級時顯示。根據預設、此層級在錯誤層級下設為3%、可透過Element API進行調整。您必須新增更多容量、或盡快釋出容量。

* *錯誤*
+
當叢集處於這種狀態時、如果節點遺失、叢集中的容量將不足以重建兩倍Helix資料保護。當叢集處於這種狀態時、新的Volume建立、複製和快照都會遭到封鎖。對於任何要進入的叢集而言、這不是安全或建議的狀態。您必須新增更多容量、或立即釋出容量。

* *重大*
+
發生此重大錯誤的原因是叢集已耗用100%。它處於唯讀狀態、無法對叢集建立新的iSCSI連線。達到此階段時、您必須立即釋出或新增更多容量。




NOTE: 下列項目適用於雙節點叢集臨界值：

* 中繼資料完整度錯誤低於嚴重錯誤20%。
* 區塊完整度錯誤是低於關鍵容量的1個區塊磁碟機（包括閒置容量）；這表示兩個區塊磁碟機的容量低於關鍵容量。

