---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: 如果一個或兩個中繼資料磁碟機故障、您可以將中繼資料（或分片）磁碟機新增回叢集、以恢復這些磁碟機。如果節點上已啟用MDSS功能、您可以在NetApp Element 支援中心UI中執行恢復作業。 
---
= 基本的MDSS磁碟機疑難排解
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當一個或兩個中繼資料磁碟機故障時、您可以將中繼資料（或分割）磁碟機新增回叢集、以恢復這些磁碟機。如果節點上已啟用MDSS功能、您可以在NetApp Element 支援中心UI中執行恢復作業。

如果節點中的任一或兩個中繼資料磁碟機都發生故障、則Slice服務將會關閉、而來自兩個磁碟機的資料將備份到節點中的不同磁碟機。

下列案例概述可能的故障情形、並提供修正問題的基本建議：



== 系統分片磁碟機故障

* 在此案例中、會驗證插槽2並返回可用狀態。
* 必須先重新填入系統磁碟機、然後才能使分片服務恢復上線。
* 當系統磁碟機可用時、您應該更換系統磁碟機、同時新增磁碟機和插槽2磁碟機。



NOTE: 您無法將磁碟機本身新增至插槽2作為中繼資料磁碟機。您必須同時將兩個磁碟機新增回節點。



== 插槽2故障

* 在此案例中、系統磁碟機已通過驗證、並返回可用狀態。
* 您應該將插槽2更換為備用插槽2、當插槽2可用時、請同時新增系統磁碟機和插槽2磁碟機。




== 系統磁碟機和插槽2故障

* 您應該將系統磁碟機和插槽2同時更換為備用磁碟機。當兩個磁碟機都可用時、請同時新增系統磁碟機和插槽2磁碟機。




== 營運順序

* 使用備用磁碟機更換故障硬碟機（如果兩個磁碟機都故障、請更換兩個磁碟機）。
* 重新填入磁碟機並處於可用狀態時、將磁碟機重新新增回叢集。




== 驗證作業

* 驗證插槽0（或內部）和插槽2中的磁碟機在「Active Drives（作用中磁碟機）」清單中是否被識別為中繼資料磁碟機。
* 確認所有的切片平衡都已完成（事件記錄中至少30分鐘內不會再出現任何移動的切片訊息）。




== 以取得更多資訊

xref:task_troubleshoot_add_mdss_drives.adoc[新增MDSS磁碟機]
