---
permalink: storage/concept_intro_custom_protection_domains.html 
sidebar: sidebar 
keywords: Protection Domain layout,user-defined,custom layout 
summary: 您可以定義自訂的「保護網域」配置、其中每個節點只與一個自訂的「保護網域」相關聯。根據預設、每個節點都會指派給相同的預設自訂保護網域。 
---
= 自訂保護網域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以定義符合特定機箱和節點配置的自訂保護網域配置。

如果未指派自訂保護網域：

* 叢集作業不受影響。
* 自訂層級既不容忍、也不彈性。


當您為叢集設定自訂保護網域時、有三種可能的保護層級、您可從元素Web UI儀表板查看：

* 不受保護：儲存叢集不受其自訂保護網域之一故障的影響。若要修正此問題、請將額外的儲存容量新增至叢集、或重新設定叢集的自訂保護網域、以保護叢集免於可能的資料遺失。
* 容錯能力：儲存叢集有足夠的可用容量、可在其中一個自訂保護網域發生故障後、防止資料遺失。
* 容錯能力：儲存叢集在其自訂保護網域之一故障後、有足夠的可用容量可自我修復。修復程序完成後、如果有其他網域發生故障、叢集將受到保護、不會遺失資料。


如果指派多個自訂保護網域、則每個子系統都會將重複項目指派給不同的自訂保護網域。如果無法這麼做、則會回復為將重複項目指派給不同的節點。每個子系統（例如、儲存槽、分片、傳輸協定端點供應商和頻道群）都會獨立執行此作業。

您可以使用元素UI來執行 link:task_data_protection_configure_custom_protection_domains.html["設定自訂保護網域"^]或使用下列API方法：

* link:../api/reference_element_api_getprotectiondomainlayout.html["GetProtectionDomainLayout"^] -顯示每個節點所在的機箱和自訂保護網域。
* link:../api/reference_element_api_setprotectiondomainlayout.html["SetProtectionDomainLayout"^] -可將自訂保護網域指派給每個節點。




== 如需詳細資訊、請參閱

link:../api/index.html["使用Element API管理儲存設備"^]
