---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: 您可以管理SolidFire 適用於某個不實儲存系統的叢集管理員帳戶。可用的叢集管理員管理功能包括建立、刪除及編輯叢集管理員帳戶、變更叢集管理員密碼、以及設定LDAP設定、以管理使用者的系統存取。 
---
= 管理叢集管理員使用者帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以SolidFire 建立、刪除及編輯叢集管理員帳戶、變更叢集管理員密碼、以及設定LDAP設定來管理使用者的系統存取、藉此管理適用於整個儲存系統的叢集管理員帳戶。



== 儲存叢集管理員帳戶類型

執行NetApp Element 下列兩種類型的系統管理員帳戶可存在於執行此軟件的儲存叢集：主叢集系統管理員帳戶和叢集系統管理員帳戶。

* *主叢集管理員帳戶*
+
此管理員帳戶是在建立叢集時建立的。此帳戶是主要管理帳戶、具有最高層級的叢集存取權。此帳戶類似於Linux系統中的root使用者。您可以變更此系統管理員帳戶的密碼。

* *叢集管理員帳戶*
+
您可以為叢集管理員帳戶提供有限的管理存取權限、以便在叢集中執行特定工作。指派給每個叢集管理員帳戶的認證資料、用於驗證儲存系統內的API和元素UI要求。




NOTE: 需要本機（非LDAP）叢集管理員帳戶、才能透過每節點UI存取叢集中的作用中節點。存取尚未屬於叢集一部分的節點時、不需要帳戶認證。



== 檢視叢集管理詳細資料

. 若要建立全叢集（非LDAP）叢集管理員帳戶、請執行下列動作：
+
.. 按一下「*使用者*>*叢集管理員*」。


. 在「使用者」索引標籤的「叢集管理員」頁面上、您可以檢視下列資訊。
+
** * ID*：指派給叢集管理員帳戶的連續編號。
** *使用者名稱*：建立叢集管理員帳戶時所指定的名稱。
** *存取*：指派給使用者帳戶的使用者權限。可能值：
+
*** 讀取
*** 報告
*** 節點
*** 磁碟機
*** 磁碟區
*** 帳戶
*** 叢集管理員
*** 系統管理員




+

NOTE: 系統管理員存取類型可使用所有權限。

+
** *類型*：叢集管理員的類型。可能值：
+
*** 叢集
*** LDAP


** *屬性*：如果叢集管理員帳戶是使用元素API建立、則此欄會顯示使用該方法設定的任何名稱值配對。
+
請參閱 link:../api/index.html["《軟件API參考》NetApp Element"]。







== 建立叢集管理員帳戶

您可以建立具有權限的新叢集管理員帳戶、以允許或限制存取儲存系統的特定區域。當您設定叢集管理員帳戶權限時、系統會針對您未指派給叢集管理員的任何權限、授予唯讀權限。

如果您想要建立LDAP叢集管理員帳戶、請先確定已在叢集上設定LDAP、然後再開始。

link:task_system_manage_enable_ldap_authentication.html["使用元素使用者介面啟用LDAP驗證"]

您可以稍後變更叢集管理員帳戶的報告權限、節點、磁碟機、磁碟區、帳戶、 和叢集層級存取。當您啟用權限時、系統會指派該層級的寫入存取權。系統會針對您未選取的層級、授予系統管理員使用者唯讀存取權。

您也可以稍後移除系統管理員所建立的任何叢集管理員使用者帳戶。您無法移除建立叢集時所建立的主要叢集管理員帳戶。

. 若要建立全叢集（非LDAP）叢集管理員帳戶、請執行下列動作：
+
.. 按一下「*使用者*>*叢集管理員*」。
.. 按一下「*建立叢集管理*」。
.. 選取*叢集*使用者類型。
.. 輸入帳戶的使用者名稱和密碼、然後確認密碼。
.. 選取要套用至帳戶的使用者權限。
.. 勾選核取方塊以同意終端使用者授權合約。
.. 按一下「*建立叢集管理*」。


. 若要在LDAP目錄中建立叢集管理員帳戶、請執行下列動作：
+
.. 按一下*叢集*>* LDAP *。
.. 確認已啟用LDAP驗證。
.. 按一下*測試使用者驗證*、然後複製顯示給使用者或使用者所屬群組之一的辨別名稱、以便稍後貼上。
.. 按一下「*使用者*>*叢集管理員*」。
.. 按一下「*建立叢集管理*」。
.. 選取LDAP使用者類型。
.. 在辨別名稱欄位中、依照文字方塊中的範例輸入使用者或群組的完整辨別名稱。或者、也可以貼上您先前複製的辨別名稱。
+
如果辨別名稱是群組的一部分、則LDAP伺服器上屬於該群組成員的任何使用者都將擁有此管理員帳戶的權限。

+
若要新增LDAP叢集管理使用者或群組、使用者名稱的一般格式為「LDAP：<完整辨別名稱>」。

.. 選取要套用至帳戶的使用者權限。
.. 勾選核取方塊以同意終端使用者授權合約。
.. 按一下「*建立叢集管理*」。






== 編輯叢集管理員權限

您可以變更叢集管理員帳戶的報告權限、節點、磁碟機、磁碟區、帳戶、 和叢集層級存取。當您啟用權限時、系統會指派該層級的寫入存取權。系統會針對您未選取的層級、授予系統管理員使用者唯讀存取權。

. 按一下「*使用者*>*叢集管理員*」。
. 針對您要編輯的叢集管理員、按一下「動作」圖示。
. 按一下 * 編輯 * 。
. 選取要套用至帳戶的使用者權限。
. 按一下*儲存變更*。




== 變更叢集管理員帳戶的密碼

您可以使用Element UI來變更叢集管理員密碼。

. 按一下「*使用者*>*叢集管理員*」。
. 針對您要編輯的叢集管理員、按一下「動作」圖示。
. 按一下 * 編輯 * 。
. 在變更密碼欄位中、輸入新密碼並加以確認。
. 按一下*儲存變更*。




== 如需詳細資訊、請參閱

* link:task_system_manage_enable_ldap_authentication.html["使用元素使用者介面啟用LDAP驗證"]
* link:concept_system_manage_manage_ldap.html["停用LDAP"]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

