---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: 系統會報告多種類型的事件；每個事件都是系統已完成的作業。事件可以是例行事件、一般事件或需要系統管理員注意的事件。「事件記錄」頁面上的「事件類型」欄會指出事件發生在系統的哪個部分。 
---
= 事件類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系統會報告多種類型的事件；每個事件都是系統已完成的作業。事件可以是例行事件、一般事件或需要系統管理員注意的事件。「事件記錄」頁面上的「事件類型」欄會指出事件發生在系統的哪個部分。


NOTE: 系統不會在事件記錄中記錄唯讀API命令。

下列清單說明事件記錄中所顯示的事件類型：

* *每個事件*
+
使用者透過API或Web UI啟動的事件、可修改設定。

* *資料夾分配事件*
+
與資料儲存槽指派相關的事件。容器基本上是儲存資料並在叢集之間對應的容器。

* *《活頁事件》*
+
與在區塊服務之間重新指派資料相關的系統事件。

* * b檢查事件*
+
與區塊服務檢查相關的系統事件。

* * bsKillEvent *
+
與區塊服務終止相關的系統事件。

* *《資本事件》*
+
與在整個磁碟區上執行的作業相關的事件、例如備份、還原、快照或複製。

* * clonewonevet*
+
與磁碟區複製相關的事件。

* *叢集主辦活動*
+
叢集初始化時或叢集組態變更時出現的事件、例如新增或移除節點。

* *相撲事件*
+
與磁碟上無效資料校驗和相關的事件。

* *資料事件*
+
與讀寫資料相關的事件。

* * db事件*
+
與叢集中所有節點所維護之通用資料庫相關的事件。

* *磁碟事件*
+
與磁碟機作業相關的事件。

* *加密At恢復 事件*
+
與叢集加密程序相關的事件。

* *《森森森森活動》*
+
與增加或減少頻道群中的節點數相關的事件。

* *光纖通道事件*
+
與節點組態和連線相關的事件。

* * gcEvent *
+
與程序相關的事件每60分鐘執行一次、以回收區塊磁碟機上的儲存空間。此程序也稱為垃圾回收。

* * iEvent *
+
內部系統錯誤。

* *安裝事件*
+
自動軟體安裝事件。軟體正在掛起的節點上自動安裝。

* * iSCSI事件*
+
與系統中iSCSI問題相關的事件。

* *限制事件*
+
與帳戶或叢集中的磁碟區或虛擬磁碟區數量接近所允許上限的相關事件。

* *維護模式事件*
+
與節點維護模式相關的事件、例如停用節點。

* *網路事件*
+
與虛擬網路狀態相關的事件。

* *平台硬體事件*
+
與在硬體裝置上偵測到的問題有關的事件。

* *刪除叢集事件*
+
與遠端叢集配對相關的事件。

* *排程器事件*
+
與排程快照相關的事件。

* *服務事件*
+
與系統服務狀態相關的事件。

* *交叉分析eEvent *
+
與Slice Server相關的事件、例如移除中繼資料磁碟機或磁碟區。

+
分區重新指派事件有三種類型、包括指派磁碟區之服務的相關資訊：

+
** 翻轉：將主要服務變更為新的主要服務
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 移動：將次要服務變更為新的次要服務
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** 剪除：從一組服務中移除磁碟區
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* * SnmpTrapEvent *
+
與SNMP設陷相關的事件。

* *狀態事件*
+
與系統統計資料相關的事件。

* * TsEvent *
+
與系統傳輸服務相關的事件。

* *意外異常*
+
與非預期系統例外狀況相關的事件。

* * ureEvent *
+
與從儲存設備讀取時發生的不可恢復讀取錯誤有關的事件。

* * vasaProviderEvent *
+
與VASA（vSphere API for Storage Aware）Provider相關的事件。


