---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: 您可以在將變更提交至網路組態之後、測試網路設定的變更。您可以執行測試、確保儲存節點穩定、而且可以在無任何問題的情況下上線。 
---
= 使用每節點UI執行系統測試
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在將變更提交至網路組態之後、測試網路設定的變更。您可以執行測試、確保儲存節點穩定、而且可以在無任何問題的情況下上線。

您已登入儲存節點的每節點UI。

. 按一下*系統測試*。
. 單擊要運行的測試旁邊的* Run Test*（運行測試）或選擇* Run All Test*（運行所有測試*）。
+

NOTE: 執行所有測試作業都會耗費大量時間、而且只能在NetApp支援部門的指示下執行。

+
** *測試連線的整體效果*
+
測試並驗證與資料庫集合的連線能力。根據預設、測試會使用節點相關聯之叢集的集合。或者、您也可以提供不同的頻道群來測試連線能力。

** *測試Connect Mvip*
+
Ping指定的管理虛擬IP（MVIP）位址、然後對MVIP執行簡單的API呼叫、以驗證連線能力。根據預設、測試會針對節點所關聯的叢集使用MVIP。

** *測試Connect Svip*
+
使用網際網路控制訊息傳輸協定（ICMP）封包Ping指定的儲存虛擬IP（SVIP）位址、這些封包符合網路介面卡上設定的最大傳輸單元（MTU）大小。然後以iSCSI啟動器的身分連線至SVIP。根據預設、測試會針對節點相關聯的叢集使用SVIP。

** *測試硬體組態*
+
測試所有硬體組態是否正確、驗證韌體版本是否正確、並確認所有磁碟機均已正確安裝並正常運作。這與原廠測試相同。

+

NOTE: 此測試需要大量資源、只有在NetApp支援部門要求時才應執行。

** *測試本機連線能力*
+
在每個節點上ping叢集IP（CIP）、以測試與叢集中所有其他節點的連線能力。只有當節點是作用中叢集的一部分時、此測試才會顯示在節點上。

** *測試定位叢集*
+
驗證節點是否能找到叢集組態中指定的叢集。

** *測試網路組態*
+
驗證已設定的網路設定是否符合系統上使用的網路設定。此測試不適用於在節點主動參與叢集時偵測硬體故障。

** *測試Ping *
+
Ping指定的主機清單、或是動態建立叢集中所有已登錄節點的清單、並ping每個節點以利簡單連線。

** *測試遠端連線*
+
在每個節點上ping叢集IP（CIP）、以測試與遠端配對叢集中所有節點的連線能力。只有當節點是作用中叢集的一部分時、此測試才會顯示在節點上。




