---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: 您可以排程磁碟區或磁碟區的快照、以指定的時間間隔自動執行。 
---
= 建立快照排程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以排程磁碟區或磁碟區的快照、以指定的時間間隔自動執行。

設定快照排程時、您可以根據每週天數或每月天數、從時間間隔中進行選擇。您也可以建立週期性排程、並指定下一次快照發生之前的天數、小時數和分鐘數。

如果您排程快照在5分鐘內不可見的時間段執行、快照將在下一個時間段執行、時間間隔為5分鐘。例如、如果您排定在12：42：00 UTC執行快照、則快照將在12：45：00 UTC執行。您無法排程快照以5分鐘以內的時間間隔執行。

從元素12.5開始、您可以從UI啟用序列建立、並選擇以先進先出（FIFO）為基礎來保留快照。

* 「*啟用序列建立*」選項指定一次只複寫一個快照。當先前的快照複寫仍在進行中時、建立新快照失敗。如果未選取此核取方塊、則當另一個快照複寫仍在進行中時、即允許建立快照。
* 「* FIFO *」選項新增了保留最新快照數量一致的功能。勾選此核取方塊時、快照會以FIFO為基礎保留。在FIFO快照佇列達到最大深度後、插入新的FIFO快照時、會捨棄最舊的FIFO快照。


.步驟
. 選擇*資料保護*>*排程*。
. 選取*建立排程*。
. 在「* Volume ID CSV*」欄位中、輸入要納入快照作業的單一Volume ID或以逗號分隔的Volume ID清單。
. 輸入新的排程名稱。
. 選取排程類型、然後從提供的選項中設定排程。
. *可選：*選擇*重複日程安排*可無限期重複快照日程安排。
. *可選：*在*新快照名稱*字段中輸入新快照的名稱。
+
如果將此欄位保留空白、系統會使用快照建立的時間和日期做為名稱。

. *選用：*選取*配對時在複寫中包含快照*核取方塊、以確保父磁碟區配對時、在複寫中擷取快照。
. *選用：*選取「*啟用序列建立*」核取方塊、以確保一次只複寫一個快照。
. 若要設定快照的保留時間、請從下列選項中選取：
+
** *選用：*選取「* FIFO（先進先出）*」核取方塊、以保留一致數量的最新快照。
** 選取*「永遠保留」*可無限期保留系統上的快照。
** 選取*設定保留期間*、然後使用日期微調方塊來選擇系統保留快照的時間長度。


. 選取*建立排程*。

