---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: 您可以設定自訂保護網域、以改善叢集的恢復能力。 
---
= 設定自訂保護網域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於包含兩個以上儲存節點的元素叢集、您可以為每個節點設定自訂保護網域。設定自訂保護網域時、您必須將叢集中的所有節點指派給網域。


TIP: 當您指派Protection Domain時、節點之間的資料會開始同步、某些叢集作業在資料同步完成之前無法使用。為叢集設定自訂保護網域之後、當您新增儲存節點時、除非您為節點指派保護網域並允許資料同步完成、否則無法為新節點新增磁碟機。請造訪 link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["Protection網域文件"] 以深入瞭解保護網域。


NOTE: 若要讓自訂保護網域配置對叢集有用、每個機箱內的所有儲存節點都必須指派給同一個自訂保護網域。您需要建立所需數量的自訂保護網域、才能做到這一點（最小的自訂保護網域配置是三個網域）。最佳做法是設定每個網域的節點數量相等、並嘗試確保指派給特定網域的每個節點都是相同類型。

.步驟
. 按一下*叢集*>*節點*。
. 按一下*設定保護網域*。
+
在「*設定自訂保護網域*」視窗中、您可以看到目前設定的保護網域（若有）、以及個別節點的保護網域指派。

. 輸入新自訂保護網域的名稱、然後按一下*「Create」（建立）*。
+
針對您需要建立的所有新保護網域重複此步驟。

. 針對「*指派節點*」清單中的每個節點、按一下「*保護網域*」欄中的下拉式清單、然後選取要指派給該節點的保護網域。
+

CAUTION: 在套用變更之前、請務必瞭解您的節點和機箱配置、您已設定的自訂保護網域配置、以及配置對資料保護的影響。如果您套用保護網域配置並立即需要進行變更、可能需要一段時間才能完成、因為套用組態後就會進行資料同步。

. 按一下*設定保護網域*。


視叢集大小而定、網域之間的資料同步資料可能需要一些時間。資料同步完成後、您可以在「*叢集*>*節點*」頁面上檢視自訂保護網域指派、而元素Web UI儀表板則會在「*自訂保護網域健全狀況*」窗格中顯示叢集的保護狀態。

套用自訂保護網域組態後、您可能會看到下列錯誤：

|===


| 錯誤 | 說明 | 解決方案 


| SetProtectionDomainLayout失敗：保護網域配置會使節點ID｛9｝無法使用。預設和非預設名稱無法同時使用。 | 節點未指派保護網域。 | 將保護網域指派給節點。 


| SetProtectionDomainLayout失敗：保護網域類型「自訂」分割保護網域類型「機箱」。 | 多節點機箱中的節點會被指派與機箱中其他節點不同的保護網域。 | 請確定機箱中的所有節點都已指派相同的保護網域。 
|===


== 如需詳細資訊、請參閱

link:concept_intro_custom_protection_domains.html["自訂保護網域"^]
link:../api/index.html["使用Element API管理儲存設備"^]
