---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: 您可以在需要更多儲存設備或建立叢集之後、將節點新增至叢集。節點第一次開機時、需要初始組態。節點設定完成後、就會顯示在待處理節點清單中、您可以將其新增至叢集。 
---
= 新增節點至叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在需要更多儲存設備或建立叢集之後、將節點新增至叢集。節點第一次開機時、需要初始組態。節點設定完成後、就會顯示在待處理節點清單中、您可以將其新增至叢集。

叢集中每個節點上的軟體版本必須相容。當您將節點新增至叢集時、叢集NetApp Element 會視需要在新節點上安裝叢集版本的資訊軟體。

您可以將容量較小或較大的節點新增至現有叢集。您可以將較大的節點容量新增至叢集、以利容量成長。必須成對新增較大的節點至具有較小節點的叢集。如此一來、如果其中一個較大的節點發生故障、就能有足夠的空間讓雙Helix移動資料。您可以將較小的節點容量新增至較大的節點叢集、以改善效能。


NOTE: 如果新增的節點佔叢集總容量的50%以上、則此節點的部分容量將無法使用（「閒置」）、因此符合容量規則。在新增更多儲存設備之前、情況仍會如此。如果新增的大型節點也不遵守容量規則、則先前閒置的節點將不再處於閒置狀態、而新新增的節點則會陷入閒置狀態。容量應一律成對新增、以避免這種情況發生。當節點變成閒置狀態時、會拋出strandedCapacity叢集故障。

https://www.youtube.com/embed/2smVHWkikXY?rel=0["NetApp影片：根據您的需求擴充：擴充SolidFire 功能"^]

您可以將節點新增至NetApp HCI 各個不相同的應用裝置。

.步驟
. 選擇*叢集*>*節點*。
. 按一下*「Pending」（待處理）*以檢視待處理節點的清單。
+
新增節點的程序完成後、會顯示在「作用中節點」清單中。在此之前、擱置中的節點會出現在「Pending Active」（擱置中的作用中）清單中。

+
將叢集新增至叢集時、可在暫掛節點上安裝叢集的元素軟體版本SolidFire 。這可能需要幾分鐘的時間。

. 執行下列其中一項：
+
** 若要新增個別節點、請按一下您要新增之節點的*「Actions」（動作）*圖示。
** 若要新增多個節點、請選取要新增之節點的核取方塊、然後選取*大量動作*。*附註：*如果您要新增的節點的Element軟體版本與叢集上執行的版本不同、叢集會非同步地將節點更新為叢集主機上執行的Element軟體版本。節點更新後、會自動將自己新增至叢集。在此非同步程序期間、節點將處於「待處理作用中」狀態。


. 按一下「 * 新增 * 」。
+
節點會出現在作用中節點清單中。





== 如需詳細資訊、請參閱

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[節點版本管理與相容性]
