---
permalink: storage/task_data_protection_back_up_volume_to_solidfire.html 
sidebar: sidebar 
keywords: volume backup, solidfire storage cluster 
summary: 您可以將位於叢集上的磁碟區備份到遠端叢集、以供執行Element軟體的儲存叢集使用。 
---
= 將磁碟區備份到SolidFire 一個不全的儲存叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將位於叢集上的磁碟區備份到遠端叢集、以供執行Element軟體的儲存叢集使用。

確保來源叢集和目標叢集已配對。

請參閱 link:task_replication_pair_clusters.html["配對叢集以進行複寫"]。

當從一個叢集備份或還原至另一個叢集時、系統會產生金鑰、作為叢集之間的驗證。此大量Volume寫入金鑰可讓來源叢集向目的地叢集進行驗證、在寫入目的地Volume時提供一定程度的安全性。在備份或還原程序中、您需要先從目的地Volume產生大量Volume寫入金鑰、然後再開始作業。

. 在目的地叢集上、*管理*>*磁碟區*。
. 按一下目的地Volume的「Actions（動作）」圖示。
. 在產生的功能表中、按一下*還原來源*。
. 在「*整合式還原*」對話方塊的「*還原自*」下、選取「* SolidFire 還原*」。
. 在*資料格式*下選取一個選項：
+
** *原生*：只SolidFire 有透過不兼容的儲存系統才能讀取的壓縮格式。
** *未壓縮*：與其他系統相容的未壓縮格式。


. 按一下「*產生金鑰*」。
. 將金鑰從*大量磁碟區寫入金鑰*方塊複製到剪貼簿。
. 在來源叢集上、前往*管理*>*磁碟區*。
. 按一下要備份之磁碟區的「動作」圖示。
. 在產生的功能表中、按一下*備份至*。
. 在*備份目標*下的*整合式備份*對話方塊中、選取* SolidFire 還原*。
. 選取您先前在*資料格式*欄位中選取的相同選項。
. 在*遠端叢集MVIP*欄位中輸入目的地Volume叢集的管理虛擬IP位址。
. 在*遠端叢集使用者名稱*欄位中輸入遠端叢集使用者名稱。
. 在*遠端叢集密碼*欄位中輸入遠端叢集密碼。
. 在*大量磁碟區寫入金鑰*欄位中、貼上您先前在目的地叢集上產生的金鑰。
. 按一下「*開始讀取*」。

