---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: 這個系統使用Volume來配置儲存設備。SolidFire磁碟區是透過iSCSI或Fibre Channel用戶端透過網路存取的區塊裝置。 
---
= 管理磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
這個系統使用Volume來配置儲存設備。SolidFire磁碟區是透過iSCSI或Fibre Channel用戶端透過網路存取的區塊裝置。

在「管理」索引標籤的「磁碟區」頁面中、您可以在節點上建立、修改、複製及刪除磁碟區。



== 建立Volume

您可以建立磁碟區、並將磁碟區與指定帳戶建立關聯。每個Volume都必須與帳戶建立關聯。此關聯可讓帳戶使用CHAP認證、透過iSCSI啟動器存取磁碟區。

您可以在建立期間指定Volume的QoS設定。

. 選擇*管理*>*磁碟區*。
. 按一下「*建立Volume *」。
. 在「*建立新磁碟區*」對話方塊中、輸入* Volume Name*。
. 輸入磁碟區的總大小。
+

NOTE: 預設的Volume大小選項為GB。您可以使用以GB或GiB為單位的大小來建立磁碟區：

+
** 1GB = 1000、000位元組
** 1GiB = 1 073 741 824位元組


. 為磁碟區選取*區塊大小*。
. 按一下「*帳戶*」下拉式清單、然後選取應可存取該磁碟區的帳戶。
+
如果帳戶不存在、請按一下「*建立帳戶*」連結、輸入新的帳戶名稱、然後按一下「*建立*」。帳戶隨即建立、並與新磁碟區建立關聯。

+

NOTE: 如果帳戶超過50個、則不會顯示清單。開始輸入、自動完成功能會顯示可能的值供您選擇。

. 若要設定*服務品質*、請執行下列其中一項：
+
.. 在* Policy*下、您可以選取現有的QoS原則（若有）。
.. 在*自訂設定*下、設定IOPS的自訂最小、最大和尖峰值、或使用預設的QoS值。
+
如果磁碟區的IOPS值大於20、000 IOPS、則可能需要高佇列深度或多個工作階段、才能在單一磁碟區上達到此IOPS等級。



. 按一下「*建立Volume *」。




== 檢視Volume詳細資料

. 選擇*管理*>*磁碟區*。
. 檢閱詳細資料。
+
** * ID*：系統產生的Volume ID。
** *名稱*：建立磁碟區時指定給該磁碟區的名稱。
** *帳戶*：指派給磁碟區的帳戶名稱。
** *存取群組*：磁碟區所屬的磁碟區存取群組名稱。
** *存取*：建立磁碟區時指派給該磁碟區的存取類型。可能值：
+
*** 讀取/寫入：接受所有讀取和寫入。
*** 唯讀：允許所有讀取活動；不允許寫入。
*** 鎖定：僅允許系統管理員存取。
*** ReplicationTarget：指定為複寫Volume配對中的目標Volume。


** *已用*：磁碟區中已用空間的百分比。
** *大小*：磁碟區的總大小（GB）。
** * Snapshot *：為磁碟區建立的快照數量。
** * QoS原則*：使用者定義的QoS原則名稱與連結。
** *最小IOPS *：保證磁碟區IOPS的最小數量。
** *最大IOPS *：磁碟區允許的最大IOPS數。
** *爆發IOPS *：在一段短時間內、磁碟區允許的最大IOPS數。預設值= 15、000。
** *屬性*：已透過API方法指派給磁碟區做為金鑰/值配對的屬性。
** * 512e*：表示是否在Volume上啟用512e。可能值：
+
*** 是的
*** 否


** *建立日期*：建立磁碟區的日期與時間。






== 檢視個別Volume詳細資料

您可以檢視個別磁碟區的效能統計資料。

. 選擇*報告*>* Volume Performance *。
. 在Volume清單中、按一下Volume的「Actions（動作）」圖示。
. 按一下*檢視詳細資料*。
+
頁面底部會出現一個紙匣、其中包含有關該磁碟區的一般資訊。

. 若要查看磁碟區的詳細資訊、請按一下*「查看更多詳細資料」*。
+
系統會顯示磁碟區的詳細資訊及效能圖表。





== 編輯作用中磁碟區

您可以修改Volume屬性、例如QoS值、Volume大小、以及計算位元組值的計量單位。您也可以修改帳戶存取、以供複寫使用或限制對磁碟區的存取。

在下列情況下、當叢集上有足夠的空間時、您可以調整磁碟區大小：

* 正常作業條件。
* 報告磁碟區錯誤或故障。
* 正在複製磁碟區。
* 正在重新同步磁碟區。


.步驟
. 選擇*管理*>*磁碟區*。
. 在* Active*視窗中、針對您要編輯的磁碟區按一下「動作」圖示。
. 按一下 * 編輯 * 。
. *選用：*變更磁碟區的總大小。
+
** 您可以增加（但不能減少）Volume的大小。您只能在單一調整大小作業中調整一個Volume的大小。垃圾回收作業和軟體升級不會中斷調整大小作業。
** 如果您要調整複寫的磁碟區大小、應該先增加指派為複寫目標的磁碟區大小。然後您可以調整來源Volume的大小。目標Volume的大小可以大於或等於來源Volume、但不能變小。


+
預設的Volume大小選項為GB。您可以使用以GB或GiB為單位的大小來建立磁碟區：

+
** 1GB = 1000、000位元組
** 1GiB = 1 073 741 824位元組


. *選用：*選取下列其中一項的不同帳戶存取層級：
+
** 唯讀
** 讀取/寫入
** 已鎖定
** 複寫目標


. *選用：*選取應可存取磁碟區的帳戶。
+
如果帳戶不存在、請按一下*建立帳戶*連結、輸入新的帳戶名稱、然後按一下*建立*。帳戶隨即建立並與磁碟區建立關聯。

+

NOTE: 如果帳戶超過50個、則不會顯示清單。開始輸入、自動完成功能會顯示可能的值供您選擇。

. *選用：*若要變更*服務品質*的選擇、請執行下列其中一項：
+
.. 在* Policy*下、您可以選取現有的QoS原則（若有）。
.. 在*自訂設定*下、設定IOPS的自訂最小、最大和尖峰值、或使用預設的QoS值。
+

NOTE: 如果您在磁碟區上使用QoS原則、可以設定自訂QoS來移除與該磁碟區的QoS原則關係。自訂QoS會覆寫及調整Volume QoS設定的QoS原則值。

+

TIP: 當您變更IOPS值時、應以數十或數百個單位遞增。輸入值需要有效的整數。

+

TIP: 設定具有極高突發值的磁碟區。這可讓系統更快處理偶爾發生的大型區塊循序工作負載、同時仍會限制磁碟區的持續IOPS。



. 按一下*儲存變更*。




== 刪除 Volume

您可以從元素儲存叢集刪除一或多個磁碟區。

系統不會立即清除已刪除的Volume、磁碟區仍可繼續使用約八小時。如果您在系統清除磁碟區之前還原磁碟區、則磁碟區會恢復連線並還原iSCSI連線。

如果刪除用於建立快照的磁碟區、其關聯的快照將會變成非作用中。當刪除的來源磁碟區被清除時、相關的非作用中快照也會從系統中移除。


IMPORTANT: 與管理服務相關的持續磁碟區會在安裝或升級期間建立並指派給新帳戶。如果您使用的是持續磁碟區、請勿修改或刪除磁碟區或其相關帳戶。

.步驟
. 選擇*管理*>*磁碟區*。
. 若要刪除單一Volume、請執行下列步驟：
+
.. 針對您要刪除的磁碟區、按一下「動作」圖示。
.. 在產生的功能表中、按一下*刪除*。
.. 確認行動。


+
系統會將磁碟區移至「* Volumes *」（*磁碟區*）頁面上的「*刪除*」區域。

. 若要刪除多個Volume、請執行下列步驟：
+
.. 在Volume清單中、核取您要刪除的任何Volume旁的方塊。
.. 按一下*大量動作*。
.. 在產生的功能表中、按一下*刪除*。
.. 確認行動。
+
系統會將磁碟區移至「* Volumes *」（*磁碟區*）頁面上的「*刪除*」區域。







== 還原刪除的Volume

如果磁碟區已刪除但尚未清除、您可以還原系統中的磁碟區。系統會在磁碟區刪除約八小時後自動清除。如果系統已清除該磁碟區、您將無法還原該磁碟區。

. 選擇*管理*>*磁碟區*。
. 按一下「*刪除*」索引標籤以檢視刪除的磁碟區清單。
. 針對您要還原的磁碟區、按一下「動作」圖示。
. 在產生的功能表中、按一下*還原*。
. 確認行動。
+
該磁碟區會放在* Active* Volume清單中、並還原與該磁碟區的iSCSI連線。





== 清除Volume

當磁碟區被清除時、它會從系統中永久移除。磁碟區中的所有資料都會遺失。

系統會在刪除八小時後自動清除刪除的磁碟區。不過、如果您想要在排程時間之前清空磁碟區、可以這麼做。

. 選擇*管理*>*磁碟區*。
. 按一下「*刪除*」按鈕。
. 執行步驟以清除單一磁碟區或多個磁碟區。
+
[cols="25,75"]
|===
| 選項 | 步驟 


 a| 
清除單一Volume
 a| 
.. 按一下您要清除之磁碟區的「動作」圖示。
.. 按一下*清除*。
.. 確認行動。




 a| 
清除多個Volume
 a| 
.. 選取您要清除的磁碟區。
.. 按一下*大量動作*。
.. 在產生的功能表中、選取*清除*。
.. 確認行動。


|===




== 複製磁碟區

您可以建立單一磁碟區或多個磁碟區的複本、以建立資料的時間點複本。當您複製磁碟區時、系統會建立磁碟區的快照、然後建立快照所參照資料的複本。這是一個非同步程序、程序所需的時間長短取決於您要複製的磁碟區大小和目前的叢集負載。

叢集一次最多可支援兩個執行中的每個Volume複製要求、一次最多可支援八個作用中Volume複製作業。超過這些限制的要求會排入佇列、以供日後處理。


NOTE: 作業系統在處理複製磁碟區的方式上各不相同。VMware ESXi會將複製的Volume視為Volume複本或Snapshot Volume。磁碟區將是可用來建立新資料存放區的可用裝置。如需掛載複製磁碟區及處理快照LUN的詳細資訊、請參閱上的VMware文件 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["掛載VMFS資料存放區複本"] 和 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["管理重複的VMFS資料存放區"]。


IMPORTANT: 在您以較小的大小複製來精簡複製的磁碟區之前、請務必先準備好分割區、使其適合較小的磁碟區。

.步驟
. 選擇*管理*>*磁碟區*。
. 若要複製單一磁碟區、請執行下列步驟：
+
.. 在「*作用中*」頁面的磁碟區清單中、按一下您要複製之磁碟區的「動作」圖示。
.. 在產生的功能表中、按一下* Clone（複製）*。
.. 在「* Clone Volume*」（*複製Volume *）視窗中、輸入新複製Volume的Volume名稱。
.. 使用「* Volume Size*」（體積大小*）選項方塊和清單、選取Volume的大小和測量值。
+

NOTE: 預設的Volume大小選項為GB。您可以使用以GB或GiB為單位的大小來建立磁碟區：

+
*** 1GB = 1000、000位元組
*** 1GiB = 1 073 741 824位元組


.. 選取新複製磁碟區的存取類型。
.. 從「*帳戶*」清單中選取要與新複製的磁碟區建立關聯的帳戶。
+

NOTE: 如果您按一下「*建立帳戶*」連結、輸入帳戶名稱、然後按一下「*建立*」、即可在此步驟中建立帳戶。系統會在您建立帳戶後、自動將其新增至*帳戶*清單。



. 若要複製多個磁碟區、請執行下列步驟：
+
.. 在「*作用中*」頁面的磁碟區清單中、核取您要複製的任何磁碟區旁的方塊。
.. 按一下*大量動作*。
.. 在產生的功能表中、選取* Clone（複製）*。
.. 在「*複製多個磁碟區*」對話方塊的「*新增磁碟區名稱前置字元*」欄位中、輸入複製磁碟區的前置字元。
.. 從「*帳戶*」清單中選取要與複製磁碟區建立關聯的帳戶。
.. 選取複製磁碟區的存取類型。


. 按一下*開始複製*。
+

NOTE: 增加實體複本的磁碟區大小、會在磁碟區結尾處產生額外可用空間的新磁碟區。視磁碟區的使用方式而定、您可能需要擴充磁碟分割區、或在可用空間中建立新的磁碟分割區、才能使用磁碟區。





== 以取得更多資訊

* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

