---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: failback, perform, source volume, snapmirror, dr, disaster recovery 
summary: 您可以使用NetAppElement UI重新同步原始來源Volume並容錯回復。本節適用於原始來源磁碟區已遺失但原始叢集仍不受影響的情況。如需如何還原至新叢集的指示、請參閱NetApp支援網站上的文件。 
---
= 當來源磁碟區不再存在時、請執行容錯回復
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NetAppElement UI重新同步原始來源Volume並容錯回復。本節適用於原始來源磁碟區已遺失但原始叢集仍不受影響的情況。如需如何還原至新叢集的指示、請參閱NetApp支援網站上的文件。

.您需要的是 #8217 ；需要的是什麼
* 您在Element ONTAP 和現象區之間有中斷的複寫關係。
* 元素磁碟區已不可恢復地遺失。
* 原始Volume名稱顯示為「找不到」。


.步驟
. 在Element UI中、找出您在執行容錯移轉時所中斷的關係。
+
*最佳實務做法：*請記下SnapMirror原則、並排程原始中斷關係的詳細資料。重新建立關係時、必須提供此資訊。

. 按一下「*動作*」圖示、然後按一下「*反轉重新同步*」。
. 確認行動。
+

NOTE: 「反向重新同步」作業會建立新的關係、使原始來源Volume和目的地Volume的角色反向（這會在原始關係持續存在時產生兩種關係）。由於原始磁碟區不再存在、系統會建立新的元素磁碟區、其Volume名稱和Volume大小與原始來源磁碟區相同。新磁碟區會指派稱為sm-recovery的預設QoS原則、並與稱為sm-recovery的預設帳戶相關聯。您將需要手動編輯SnapMirror所建立之所有磁碟區的帳戶和QoS原則、以取代已銷毀的原始來源磁碟區。

+
最新快照的資料會傳輸至新磁碟區、作為反轉重新同步作業的一部分。您可以繼續存取資料並將資料寫入目的地端的作用中磁碟區、但您必須先中斷所有主機與作用中磁碟區的連線、然後執行SnapMirror更新、才能在後續步驟中恢復原始的主要關係。完成反轉重新同步並確定目的地端的磁碟區沒有連線到作用中工作階段、且最新資料位於原始主要磁碟區之後、請繼續執行下列步驟以完成容錯回復並重新啟動原始主要磁碟區：

. 按一下「反轉重新同步」作業期間所建立之反關係的*「動作」*圖示、然後按一下「*中斷*」。
. 按一下來源磁碟區不存在的原始關聯*動作*圖示、然後按一下*刪除*。
. 按一下您在步驟4中中斷的反關係*動作*圖示、然後按一下*反轉重新同步*。
. 這會反轉來源和目的地、並與原始關係建立相同的磁碟區來源和磁碟區目的地關係。
. 按一下「*動作*」圖示和「*編輯*」、以更新您注意到的原始QoS原則和排程設定。
. 現在可以安全地刪除您在步驟6中重新同步的反轉關係。




== 如需詳細資訊、請參閱

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror容錯回復案例]
