---
permalink: storage/task-element-replication-create-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, element, source, destination 
summary: 您可以使用 SnapMirror 將元素 Volume 的快照複本複寫到 ONTAP 目的地系統。萬一Element站台發生災難、您可以從ONTAP 該系統將資料提供給用戶端、然後在恢復服務時重新啟動Element來源Volume。 
---
= 建立從元素來源到ONTAP 目的地的關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一線儲存設備中的來源磁碟區與二線儲存設備中的目的地磁碟區之間的關係稱為_DATA保護關係_。您可以使用 `snapmirror create`命令建立資料保護關係、從元素來源到 ONTAP 目的地、或從 ONTAP 來源到元素目的地。

您可以使用 SnapMirror 將元素 Volume 的快照複本複寫到 ONTAP 目的地系統。萬一Element站台發生災難、您可以從ONTAP 該系統將資料提供給用戶端、然後在恢復服務時重新啟動Element來源Volume。

.開始之前
* 包含要複寫之磁碟區的元素節點必須可供ONTAP 支援的項目。
* 必須已啟用元素Volume才能進行SnapMirror複寫。
* 如果您使用「鏡射資料保險箱」原則類型、則必須設定 SnapMirror 標籤、才能複寫元素快照複本。
+
[NOTE]
====
您只能在或中執行此工作link:concept_snapmirror_labels.html["Element 軟體 Web UI"]link:../api/concept_element_api_snapshots_overview.html["API方法"]。

====


.關於這項工作
您必須以格式指定元素來源路徑 `<hostip:>/lun/<name>`、其中「 'lun' 」是實際字串「 'lun' 」、 `name` 是元素 Volume 的名稱。

元素Volume大致相當ONTAP 於一個實體LUN。當元素軟體與ONTAP SnapMirror之間的資料保護關係初始化時、SnapMirror會建立一個名稱為Element Volume的LUN。如果LUN符合從Element軟體複製到ONTAP SnapMirror的要求、SnapMirror會將資料複寫到現有LUN。

複寫規則如下：

* 僅一個元素磁碟區的資料可包含在其中。ONTAP
* 您無法將資料從ONTAP 一個現象磁碟區複製到多個元素磁碟區。


在 ONTAP 9 3 及更早版本中、目的地磁碟區最多可包含 251 份快照複本。在 ONTAP 9 的 4 和更新版本中、目的地磁碟區最多可包含 1019 個快照複本。

.步驟
. 從目的地叢集建立從元素來源到ONTAP 目的地的複寫關係：
+
`snapmirror create -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -schedule schedule -policy <policy>`

+
如需完整的命令語法、請參閱手冊頁。

+
下列範例使用預設原則建立 SnapMirror DR 關係 `MirrorLatest`：

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
下列範例使用預設原則建立統一複寫關係 `MirrorAndVault`：

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
下列範例使用原則建立統一化的複寫關係 `Unified7year`：

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
下列範例使用自訂原則建立統一化的複寫關係 `my_unified`：

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.完成後
使用 `snapmirror show`命令驗證是否已建立 SnapMirror 關係。如需完整的命令語法、請參閱手冊頁。
