---
permalink: storage/task_data_manage_vvol_enable_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volumes, enable, functionality on the cluster, vvols 
summary: 您必須透過NetApp Element VMware軟體手動啟用vSphere Virtual Volumes（VVols）功能。Element軟體系統預設會停用VVols功能、而且不會在新安裝或升級時自動啟用。啟用VVols功能是一次性的組態工作。 
---
= 啟用虛擬磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須透過NetApp Element VMware軟體手動啟用vSphere Virtual Volumes（VVols）功能。Element軟體系統預設會停用VVols功能、而且不會在新安裝或升級時自動啟用。啟用VVols功能是一次性的組態工作。

.您需要的產品
* 叢集必須執行元件9.0或更新版本。
* 叢集必須連線至與VVols相容的ESXi 6.0或更新版本環境。
* 如果您使用的是元素11.3或更新版本、則叢集必須連線至ESXi 6.0更新3或更新版本的環境。



IMPORTANT: 啟用vSphere Virtual Volumes功能會永久變更元素軟體組態。只有當叢集連線至VMware ESXi VVols相容的環境時、才應啟用VVols功能。您只能將叢集還原至原廠映像、以停用VVols功能並還原預設設定、這會刪除系統上的所有資料。

.步驟
. 選擇*叢集*>*設定*。
. 尋找虛擬磁碟區的叢集專屬設定。
. 按一下「*啟用虛擬磁碟區*」。
. 按一下「*是*」以確認「虛擬磁碟區」組態變更。
+
「* VVols *」標籤會出現在元素UI中。

+

NOTE: 啟用VVols功能後、SolidFire 即可啟動VASA Provider、開啟VASA流量的連接埠844,並建立vCenter和所有ESXi主機可探索的傳輸協定端點。

. 從*叢集*>*設定*中的虛擬磁碟區（VVols）設定複製VASA Provider URL。您將使用此URL在vCenter中登錄VASA Provider。
. 在* VVols *>* Storage Containers*中建立儲存容器。
+

NOTE: 您必須至少建立一個儲存容器、以便將VM資源配置到VVOL資料存放區。

. 選擇* VVolS*>*傳輸協定端點*。
. 確認已為叢集中的每個節點建立傳輸協定端點。
+

NOTE: vSphere還需要其他組態工作。請參閱《VMware vSphere Virtual Volumes for SolidFire VMware Storage組態指南》_、在vCenter中註冊VASA Provider、建立及管理VVOL資料存放區、以及根據原則管理儲存設備。





== 如需詳細資訊、請參閱

https://www.netapp.com/us/media/tr-4642.pdf["《VMware vSphere Virtual Volumes for SolidFire VMware儲存組態指南》"]
