---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: 您可以使用儲存節點的每節點UI來建立或刪除支援套件、重設磁碟機的組態設定、以及重新啟動網路或叢集服務。 
---
= 使用每節點UI執行系統公用程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用儲存節點的每節點UI來建立或刪除支援套件、重設磁碟機的組態設定、以及重新啟動網路或叢集服務。

您已登入儲存節點的每節點UI。

. 按一下*系統公用程式*。
. 按一下您要執行之系統公用程式的按鈕。
+
** *控制能力*
+
重新開機、重新開機或關機節點。

+

IMPORTANT: 這項作業會造成網路連線暫時中斷。

+
指定下列參數：

+
*** 行動：選項包括重新啟動和停止（關機）。
*** 叫醒延遲：節點恢復連線之前的任何額外時間。


** *收集節點記錄*
+
在節點的/tmp/bundles目錄下建立支援服務包。

+
指定下列參數：

+
*** 套裝組合名稱：所建立之每個支援套裝組合的唯一名稱。如果未提供名稱、則會使用「supportBundle」和節點名稱做為檔案名稱。
*** 額外的args：此參數會饋送至SF_make支援套件指令碼。此參數僅應應應NetApp支援部門要求使用。
*** 超時秒數：指定每個ping回應等待的秒數。


** *刪除節點記錄*
+
刪除節點上使用*建立叢集支援產品組合*或Create SupportBundle API方法所建立的任何目前支援產品組合。

** *重設磁碟機*
+
初始化磁碟機、並移除目前位於磁碟機上的所有資料。您可以在現有節點或升級的節點中重複使用磁碟機。

+
指定下列參數：

+
*** 磁碟機：要重設的裝置名稱（非磁碟機ID）清單。


** *重設網路組態*
+
協助解決個別節點的網路組態問題、並將個別節點的網路組態重設為原廠預設值。

** *重設節點*
+
將節點重設為原廠設定。系統會移除所有資料、但在此作業期間會保留節點的網路設定。只有在節點未指派給叢集且處於可用狀態時、才能重設節點。

+

IMPORTANT: 使用此選項時、所有資料、套件（軟體升級）、組態和記錄檔都會從節點刪除。

** *重新啟動網路*
+
重新啟動節點上的所有網路服務。

+

IMPORTANT: 這項作業可能會導致網路連線暫時中斷。

** *重新啟動服務*
+
在節點上重新啟動元素軟體服務。

+

IMPORTANT: 此作業可能會造成暫時性的節點服務中斷。您只能在NetApp支援部門的指示下執行此作業。

+
指定下列參數：

+
*** 服務：要重新啟動的服務名稱。
*** 行動：對服務執行的行動。選項包括開始、停止和重新啟動。





