---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: 在支援功能的儲存系統中、使用者帳戶可讓用戶端連線至節點上的磁碟區。SolidFire當您建立Volume時、該磁碟區會指派給特定的使用者帳戶。 
---
= 使用使用者帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在支援功能的儲存系統中、使用者帳戶可讓用戶端連線至節點上的磁碟區。SolidFire當您建立Volume時、該磁碟區會指派給特定的使用者帳戶。

帳戶包含存取指派給它的磁碟區所需的CHAP驗證。

帳戶最多可指派2、000個磁碟區、但一個磁碟區只能屬於一個帳戶。



== 建立帳戶

您可以建立帳戶以允許存取磁碟區。

系統中的每個帳戶名稱都必須是唯一的。

. 選擇*管理*>*帳戶*。
. 按一下「*建立帳戶*」。
. 輸入*使用者名稱*。
. 在「* CHAP設定*」區段中、輸入下列資訊：
+

NOTE: 將認證欄位保留空白、以自動產生任一密碼。

+
** *用於CHAP節點工作階段驗證的啟動器機密*。
** *用於CHAP節點工作階段驗證的目標機密*。


. 按一下「*建立帳戶*」。




== 檢視帳戶詳細資料

您可以以圖形格式檢視個別帳戶的績效活動。

圖表資訊提供帳戶的I/O和處理量資訊。「平均」和「尖峰」活動層級會以10秒報告期間為單位遞增顯示。這些統計資料包括指派給帳戶的所有磁碟區活動。

. 選擇*管理*>*帳戶*。
. 按一下帳戶的「動作」圖示。
. 按一下*檢視詳細資料*。


以下是一些詳細資料：

* *狀態*：帳戶狀態。可能值：
+
** 作用中：作用中帳戶。
** 鎖定：鎖定的帳戶。
** 已移除：已刪除及清除的帳戶。


* *作用中磁碟區*：指派給帳戶的作用中磁碟區數目。
* *壓縮*：指派給帳戶之磁碟區的壓縮效率分數。
* *重複資料刪除*：指派給帳戶之磁碟區的重複資料刪除效率分數。
* *精簡配置*：指派給帳戶之磁碟區的精簡配置效率分數。
* *整體效率*：指派給帳戶之磁碟區的整體效率分數。




== 編輯帳戶

您可以編輯帳戶以變更狀態、變更CHAP機密或修改帳戶名稱。

在帳戶中修改CHAP設定、或是從存取群組移除啟動器或磁碟區、可能會導致啟動器在非預期情況下失去對磁碟區的存取權。若要驗證Volume存取不會意外遺失、請務必登出會受帳戶或存取群組變更影響的iSCSI工作階段、並在完成啟動器設定和叢集設定的任何變更後、確認啟動器可以重新連線至磁碟區。


IMPORTANT: 與管理服務相關的持續磁碟區會指派給在安裝或升級期間建立的新帳戶。如果您使用的是持續磁碟區、請勿修改或刪除其相關帳戶。

. 選擇*管理*>*帳戶*。
. 按一下帳戶的「動作」圖示。
. 在產生的功能表中、選取*編輯*。
. *選用：*編輯*使用者名稱*。
. *選用：*按一下「*狀態*」下拉式清單、然後選取不同的狀態。
+

IMPORTANT: 將狀態變更為*鎖定*會終止所有與該帳戶的iSCSI連線、且該帳戶將無法再存取。與帳戶相關聯的磁碟區會保留、但磁碟區不會被iSCSI發現。

. *可選：*在* CHAP Settings*下、編輯*啟動器機密*和*目標機密*用於節點工作階段驗證的認證資料。
+

NOTE: 如果您未變更* CHAP設定*認證、則其維持不變。如果您將認證欄位設為空白、系統會產生新密碼。

. 按一下*儲存變更*。




== 刪除帳戶

您可以在不再需要時刪除帳戶。

刪除帳戶之前、請先刪除並清除與帳戶相關聯的任何磁碟區。


IMPORTANT: 與管理服務相關的持續磁碟區會指派給在安裝或升級期間建立的新帳戶。如果您使用的是持續磁碟區、請勿修改或刪除其相關帳戶。

. 選擇*管理*>*帳戶*。
. 按一下您要刪除之帳戶的「動作」圖示。
. 在產生的功能表中、選取*刪除*。
. 確認行動。




== 如需詳細資訊、請參閱

* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

