---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: 您必須先設定個別節點、才能將其新增至叢集。在機架單元中安裝節點並連接纜線並開啟節點之後、您可以使用每節點UI或節點終端機使用者介面來設定節點網路設定。 
---
= 設定儲存節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先設定個別節點、才能將其新增至叢集。在機架單元中安裝節點並連接纜線並開啟節點之後、您可以使用每節點UI或節點終端使用者介面（TUI）來設定節點網路設定。繼續之前、請先確認您擁有節點的必要網路組態資訊。

配置儲存節點有兩種選項：

* <<使用每節點UI來設定儲存節點,每節點UI>>：使用每節點UI (https://<node_management_IP>:442)[] 設定節點網路設定。
* <<使用TUI設定儲存節點,TUI>>：使用節點終端使用者介面（TUI）來設定節點。


您無法將具有DHCP指派IP位址的節點新增至叢集。您可以使用DHCP IP位址、在每個節點UI、TUI或API中初始設定節點。在此初始組態期間、您可以新增靜態IP位址資訊、以便將節點新增至叢集。

初始組態之後、您可以使用節點的管理IP位址來存取節點。然後您可以變更節點設定、將其新增至叢集、或使用節點建立叢集。您也可以使用Element軟體API方法來設定新節點。


NOTE: 從Element 11.0版開始、節點可設定為使用IPv4、IPv6或兩者的管理網路位址。這適用於儲存節點和管理節點、但不支援IPv6的管理節點11.3及更新版本除外。建立叢集時、只能使用單一的IPv4或IPv6位址來執行MVIP、而且必須在所有節點上設定對應的位址類型。



== 使用每節點UI來設定儲存節點

您可以使用每個節點的使用者介面來設定節點。

.關於這項工作
* 您可以將節點設定為具有IPV4或IPV6位址。
* 您需要TUI中顯示的DHCP位址來存取節點。您無法使用DHCP位址將節點新增至叢集。
+

IMPORTANT: 您應該為個別子網路設定管理（Bond1G）和儲存（Bond10G）介面。針對相同子網路設定的Bond1G和Bond10G介面、會在透過Bond1G介面傳送儲存流量時造成路由問題。如果管理和儲存流量必須使用相同的子網路、請手動設定管理流量以使用Bond10G介面。您可以使用每個節點UI的「*叢集設定*」頁面、為每個節點執行此動作。



.步驟
. 在瀏覽器視窗中、輸入節點的DHCP IP位址。
+
您必須新增副檔名「：4442」才能存取節點、例如 https://172.25.103.6:442[]。

+
「*網路設定*」標籤隨即開啟、並顯示「* Bond1G*」區段。

. 輸入1G管理網路設定。
. 按一下*套用變更*。
. 按一下「* Bond10G*」以顯示10G儲存網路設定。
. 輸入10G儲存網路設定。
. 按一下*套用變更*。
. 按一下*叢集設定*。
. 輸入10G網路的主機名稱。
. 輸入叢集名稱。
+

IMPORTANT: 必須先將此名稱新增至所有節點的組態、才能建立叢集。叢集中的所有節點都必須具有相同的叢集名稱。叢集名稱區分大小寫。

. 按一下*套用變更*。




== 使用TUI設定儲存節點

您可以使用終端使用者介面（TUI）來執行新節點的初始組態。

您應該為個別子網路設定Bond1G（管理）和Bond10G（儲存）介面。為相同子網路設定的Bond1G和Bond10G介面、會在透過Bond1G介面傳送儲存流量時、導致路由問題。如果管理和儲存流量必須使用相同的子網路、請手動設定管理流量以使用Bond10G介面。您可以使用元素UI的「*叢集*>*節點*」頁面為每個節點執行此動作。

.步驟
. 將鍵盤和顯示器連接至節點、然後開啟節點電源。
+
TUI的NetApp儲存主功能表會出現在tty1終端機上。

+

NOTE: 如果節點無法連線到組態伺服器、TUI會顯示錯誤訊息。請檢查組態伺服器連線或網路連線、以解決此錯誤。

. 選擇*網路*>*網路組態*。
+

TIP: 若要瀏覽功能表、請按下向上或向下箭頭鍵。若要移至其他按鈕或按鈕中的欄位、請按*選項卡*。若要在欄位之間瀏覽、請使用向上或向下箭頭鍵。

. 選取「* Bond1G（管理）*」或「* Bond10G（儲存）*」、以設定節點的1G和10G網路設定。
. 若為「邦德模式」和「狀態」欄位、請按*選項卡*以選取「說明」按鈕、並識別可用的選項。
+
叢集中的所有節點都必須具有相同的叢集名稱。叢集名稱區分大小寫。如果DHCP伺服器正在使用可用IP位址的網路上執行、則1GbE位址會出現在位址欄位中。

. 按*選項卡*選擇*確定*按鈕並儲存變更。
+
節點會處於擱置狀態、並可新增至現有叢集或新叢集。





== 如需詳細資訊、請參閱

* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

