---
permalink: esds/concept_esds_networking_best_practices.html 
sidebar: sidebar 
keywords: solidfire esds, software-defined storage, networks, linux host routing, networking 
summary: 安裝SolidFire 完RESEDSs之前、您應該先在執行RHEL的儲存節點上設定所需的網路。您負責環境中的網路路由。您可以使用提供的最佳實務做法做為架構。 
---
= 網路組態考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝SolidFire 完RESEDSs之前、您應該先在執行RHEL的儲存節點上設定所需的網路。您負責環境中的網路路由。您可以使用提供的最佳實務做法做為架構。

[IMPORTANT]
====
* 使用連結或成組的介面。
* 對叢集中的所有節點使用相同的介面名稱（例如：每個節點的管理介面使用team -mgt、以及每個節點的儲存介面使用team -stg）。
* 確定已執行Network Manager。
* 確保所有儲存節點上都已安裝有NETWORKManager-tr分派 者路由規則套件、以進行原則型路由傳送。
* 請參閱 https://www.netapp.com/us/media/tr-4763.pdf["NetApp SolidFire 不限儲存系統上的網路與網路維護最佳實務做法"]。
* 設定每個節點上的管理和儲存網路、透過連結或群組組組態使用多個備援實體介面。


====
如需網路群組的相關資訊、請參閱 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-configure_network_teaming["設定網路群組"^]。根據預設、所有儲存節點10GbE介面都會啟用9000位元組的最大傳輸單元（MTU）。為獲得最佳效能、請使用與NetApp SolidFire 等儲存節點相同的MTU來設定所有伺服器端儲存介面。您應該設定網路交換器、以支援至少9016位元組或更多的MTU、以因應巨型框架的負荷、並透過網路適當轉送。如果您想要變更此組態以支援較低的MTU設定、請聯絡NetApp支援部門。

請參閱下表、以瞭解SolidFire 有關不同流量類型所需的儲存與管理網路資訊：

[cols="2*"]
|===
| 網路類型 | 說明 


 a| 
儲存網路
 a| 
* 包括所有儲存設備/iSCSI流量。
* 如果您想要從位於不同第3層網路的主機掛載、或是打算在叢集之間複寫資料、則可以路由傳送。
* 應在同一個第2層廣播網域上設定網路介面。




 a| 
管理網路
 a| 
* 包括所有管理流量。
* 如果您想從不同的第3層網路存取叢集API或UI、就可以進行路由傳送。
* 應在同一個第2層廣播網域上設定網路介面。
* 應設定至少1500位元組MTU的網路介面卡。


|===

TIP: 如需設定主機網路的範例和秘訣、請參閱 link:task_esds_configure_the_interface_config_files.adoc["請按這裡"]。



== 如需詳細資訊、請參閱

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 資源頁面"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["先前版本的NetApp SolidFire 產品及元素產品文件"^]

