---
permalink: esds/reference_esds_sf_sds_config_file.html 
sidebar: sidebar 
keywords: element, solidfire esds, hardware components, configuration file 
summary: 每個節點都有一個SF_SDM_config.yaml檔案、其中包含SolidFire 您指定要由哪些硬體用於哪些支援。更換磁碟機之後、您必須在此檔案中新增更換磁碟機的節點資訊。此檔案會儲存在/opt/sf/中。此檔案包含節點中磁碟機的所有相關資訊。每次新增磁碟機時、您都必須在此檔案中輸入新磁碟機的詳細資料。 
---
= SF_SDs_config.yaml檔案的內容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個節點都有一個「shf_SDS _config.yaml」檔案、其中包含SolidFire 您指定供「ESXe ESDS」服務使用的硬體清單。更換磁碟機之後、您應該在此檔案中新增更換磁碟機的節點資訊。此檔案儲存在「/opt/sf/」中。此檔案包含節點中磁碟機的所有相關資訊。每次新增磁碟機時、您都應該在此檔案中輸入新磁碟機的詳細資料。

以下是*必要*的檔案內容：

[cols="4*"]
|===
| 金鑰 | 預設 | 類型 | 說明 


 a| 
schemaVersion
 a| 
「2.0」
 a| 
字串
 a| 
檔案的架構版本編號。



 a| 
網路
 a| 
不適用
 a| 
清單
 a| 
允許的值：管理介面、storageInterface



 a| 
管理介面
 a| 
"團隊0"
 a| 
字串
 a| 
用於管理和叢集管理流量的預先設定備援主機OS網路介面名稱。



 a| 
storageInterface
 a| 
"團隊1"
 a| 
字串
 a| 
用於儲存網路流量（iSCSI流量）的預先設定備援主機OS網路介面名稱。



 a| 
資料磁碟機
 a| 
不適用
 a| 
清單
 a| 
指向實體儲存裝置的主機OS路徑清單SolidFire 、由EESDS使用。您可以將此指定為區塊或NVMe裝置的完整路徑。以下是支援的完整路徑範例：/dev/disk/by-id/WWN-xxxx-xxxx-exp範例、/dev/disk/by-uid/nNVMe -xxxx-xxxx-ex-exp範例、以及/dev/sda1



 a| 
快取裝置
 a| 
不適用
 a| 
清單
 a| 
實體裝置的主機作業系統路徑、SolidFire 由EESDS用作快取裝置。您應該將其指定為清單項目。以下是支援的完整路徑範例：/dev/disk/by-id/NVMe NVMe。8086-XXXXXXX-XXXXX-XXXXX-XXXXXX

|===


== 如需詳細資訊、請參閱

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 資源頁面"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["先前版本的NetApp SolidFire 產品及元素產品文件"^]

