---
permalink: esds/reference_esds_containerlogs.html 
sidebar: sidebar 
keywords: element, solidfire esds, get container logs, sds containers 
summary: 深入瞭解SolidFire RESEDSDS容器、以及取得相關記錄的位置。此處提供的資訊可協助您開始收集記錄以進行疑難排解。最好是接洽NetApp支援部門、由訓練有素且精通記錄分析的工程師來協助解決問題。 
---
= 收集容器記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
深入瞭解SolidFire RESEDSDS容器、以及取得相關記錄的位置。此處提供的資訊可協助您開始收集記錄以進行疑難排解。這是最好的接洽方式 https://www.netapp.com/company/contact-us/support/["NetApp支援"^]（這是經過訓練且精通記錄分析的工程師、可協助解決問題。

ESXDS包括下列容器：SolidFire

* Element Container（「Element」）：將所有元素服務裝載在單一容器中。
* Element auth Container（「Element驗證」）：為管理UI提供多因素驗證（MFA）和工作階段驗證權杖。
* 網路監控容器（「sfnetwd」）：提供本機元素執行個體的活動訊號監控、以及虛擬IP（MVIP和SVIP）的容錯移轉。


若要透過SSH存取ESDS節點上的容器、節點擁有者應啟用SSH並提供登入認證。在SSH存取主機系統之後、您可以使用「podman ps」命令來檢查一或多個容器的狀態。請參閱下列範例：

[listing]
----
# podman ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f6b8817c024a localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 10 seconds ago sfnetwd
c3fed6141259 localhost/solidfire-auth:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 11 seconds ago element_auth
1ffa8289c701 localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 12 seconds ago Up 12 seconds ago element
#
----

IMPORTANT: 如果其中一個容器沒有啟動或執行、請勿使用Podman直接控制（停止或啟動）容器。Element軟體是透過SolidFire 「支援系統」服務單元來控制。此服務使用「Element（元素）」來協調在三個元素容器中執行的軟體。建議您使用「stystemctl」來控制SolidFire 主機上的支援功能、以便在任何節點上啟動和停止元素軟體；不過、在即時叢集上執行此作業時、只能在Support的指導下執行。

所有與ESXESDS相關的記錄SolidFire 都可在主機上的「/var/log/solidfire/」中找到、該主機會在所有容器執行個體之間持續存在。此目錄包含來自元素容器的記錄檔、其中包含「Element驗證/」和「sfnetwd/」子目錄、分別包含來自「Element驗證」和「sfnetwd」容器的記錄檔。從容器內部、您可以存取「/var/log/log」中的容器專屬記錄。



=== 使用NetApp混合雲控制UI來收集記錄

您可以收集記錄以傳送給NetApp支援部門、以協助診斷SolidFire 有關您的EESDS叢集的問題。

收集記錄時、請謹記下列考量事項：

* 請勿使用Podman命令來收集記錄。
* NetApp Support使用一組收集器來收集主機記錄。若要獲得最佳的支援體驗、您應該安裝一個Collect。


.步驟
. 在網頁瀏覽器中開啟管理節點的IP位址。例如：
+
[listing]
----
https://[management node IP address]
----
. 提供儲存叢集管理員認證資料、以登入NetApp混合雲控制系統。
. 從儀表板中、選取右上角的功能表。
. 選取*收集記錄*。
. 在*日期範圍*下拉式功能表中選取日期範圍、以指定記錄應包含的日期。
+
如果您指定自訂開始日期、可以選取開始日期範圍的日期。記錄會從該日期收集到目前為止。

. 在「*記錄收藏*」區段中、選取儲存叢集或特定的儲存節點。
. 選取*收集記錄*以開始收集記錄。
+
記錄收集會在背景執行、頁面會顯示進度。

+

NOTE: 視您收集的記錄而定、進度列可能會維持在某個百分比數分鐘、或在某些時間點進展非常緩慢。

. 選取*下載Logs*以下載記錄套件。
+
日誌套件為壓縮的UNIX「.tgz」檔案格式。





== 如需詳細資訊、請參閱

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 資源頁面"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["先前版本的NetApp SolidFire 產品及元素產品文件"^]

