---
permalink: api/reference_element_api_getsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,information,info,get,getting 
summary: 您可以使用GetSnmpInfo方法取得目前的簡單網路管理傳輸協定（SNMP）組態資訊。 
---
= GetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「GetSnmpInfo」方法取得目前的簡單網路管理傳輸協定（SNMP）組態資訊。



== 參數


NOTE: GetSnmpInfo不適用於元素8.0版之後的版本。。 xref:reference_element_api_getsnmpstate.adoc[GetSnmpState] 和 xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] 方法取代GetSnmpInfo方法。

此方法沒有輸入參數。



== 傳回值

此方法具有下列傳回值：

|===
| 名稱 | 說明 | 類型 


 a| 
網路
 a| 
已啟用SNMP的網路和存取類型清單。*附註：*網路僅會在SNMP v3停用時顯示。
 a| 
xref:reference_element_api_network_snmp.adoc[網路]



 a| 
已啟用
 a| 
指出叢集中的節點是否已設定為使用SNMP。可能值：

* 是的
* 錯

 a| 
布林值



 a| 
已啟用snmpV3
 a| 
如果叢集中的節點已設定為使用SNMP v3。可能值：

* 是的
* 錯

 a| 
布林值



 a| 
使用者
 a| 
如果啟用SNMP v3、則會從叢集傳回SNMP的使用者存取參數清單。會傳回此項目、而非networks參數。
 a| 
xref:reference_element_api_usmuser.adoc[使用者]

|===


== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
   "method": "GetSnmpInfo",
   "params": {},
   "id" : 1
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
   "id" : 1,
   "result" : {
      "enabled" : true,
      "networks" : [
         {
            "access" : "rosys",
            "cidr" : 0,
            "community" : "public",
            "network" : "localhost"
         }
      ]
   }
}
----


== 新的自版本

9.6



== 如需詳細資訊、請參閱

* xref:reference_element_api_getsnmpstate.adoc[GetSnmpState]
* xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL]

