---
permalink: api/reference_element_api_createsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,create,creating,snapshot,snapshots,CreateSnapshot 
summary: 您可以使用Create Snapshot建立磁碟區的時間點複本。您可以從任何磁碟區或現有的快照建立快照。 
---
= 建立Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「Create Snapshot」建立磁碟區的時間點複本。您可以從任何磁碟區或現有的快照建立快照。

如果您未使用此API方法提供SnapshotID、則會從磁碟區的作用中分支建立快照。如果要將建立快照的磁碟區複寫到遠端叢集、也可以將快照複寫到相同的目標。使用enableRemoteReplication參數來啟用快照複寫。


NOTE: 如果叢集完整度處於階段1、2或3、您可以建立快照。叢集完整度達到階段4或5時、您無法建立快照。



== 參數

此方法具有下列輸入參數：

|===
| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
屬性
 a| 
Json物件格式的名稱-值配對清單。
 a| 
Json物件
 a| 
無
 a| 
否



 a| 
「enableRemoteReplication」
 a| 
指定是否將快照複寫至遠端儲存設備。可能值：

* 「真的」：快照將複寫到遠端儲存設備。
* 「假」：快照不會複寫到遠端儲存設備。

 a| 
布林值
 a| 
錯
 a| 
否



| 「EnureSerialCreation」  a| 
指定如果正在進行先前的快照複寫、則不應建立快照。可能的值包括：

* 「真的」：這可確保一次只複寫一個快照。如果先前的快照複寫仍在進行中、建立新快照將會失敗。
* 「假」：預設。如果另一個快照複寫仍在進行中、則允許建立此快照。

| 布林值 | 「假」 | 否 


| 過期時間  a| 
指定快照可移除的時間。無法與"REtion"一起使用。如果未指定過期時間或保留時間、則快照不會過期。時間格式為ISO 8601日期字串、適用於基於時間的到期日、否則將不會過期。如果值為「null」、則會永久保留快照。如果值為「fifo」、則快照將會以先進先出的方式保留、而非與磁碟區上的其他FIFO快照相比。如果沒有可用的FIFO空間、API將會失敗。
| 字串 | 無 | 否 


 a| 
名稱
 a| 
快照的名稱。如果未輸入名稱、則會使用拍攝快照的日期和時間。名稱長度上限為255個字元。
 a| 
字串
 a| 
無
 a| 
否



 a| 
《狀態》
 a| 
此參數與「過期時間」參數相同、但時間格式為hh：mms如果既未指定「過期時間」、也未指定「保留時間」、則快照不會過期。
 a| 
字串
 a| 
無
 a| 
否



 a| 
「napMirrorLabel」
 a| 
SnapMirror軟體用來指定SnapMirror端點上的快照保留原則的標籤。
 a| 
字串
 a| 
無
 a| 
否



 a| 
「快照ID」
 a| 
用於建立新快照的快照的唯一ID。傳遞的SnapshotID必須是指定磁碟區上的快照。
 a| 
整數
 a| 
無
 a| 
否



 a| 
「volumeID」
 a| 
要複製之Volume映像的唯一ID。
 a| 
整數
 a| 
無
 a| 
是的

|===


== 傳回值

此方法具有下列傳回值：

|===


| 名稱 | 說明 | 類型 


 a| 
Checksum
 a| 
代表儲存快照中正確數字的字串。此Checksum稍後可用於比較其他快照、以偵測資料中的錯誤。
 a| 
字串



 a| 
Snapshot ID
 a| 
新快照的唯一ID。
 a| 
Snapshot ID



 a| 
Snapshot
 a| 
包含新建立之快照相關資訊的物件。
 a| 
xref:reference_element_api_snapshot.adoc[Snapshot]

|===


== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
   "method": "CreateSnapshot",
   "params": {
      "volumeID": 1
   },
   "id": 1
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
    "checksum": "0x0",
      "snapshot": {
        "attributes": {},
        "checksum": "0x0",
        "createTime": "2016-04-04T17:14:03Z",
        "enableRemoteReplication": false,
        "expirationReason": "None",
        "expirationTime": null,
        "groupID": 0,
        "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
        "name": "2016-04-04T17:14:03Z",
        "snapshotID": 3110,
        "snapshotUUID": "6f773939-c239-44ca-9415-1567eae79646",
        "status": "done",
        "totalSize": 5000658944,
        "virtualVolumeID": null,
        "volumeID": 1
      },
        "snapshotID": 3110
  }
}
----


== 例外狀況

當調用「建立Snapshot」API且無法建立快照時、會顯示xNotPrimary例外狀況。這是預期的行為。重試「建立Snapshot」API呼叫。



== 新的自版本

9.6
