---
permalink: api/reference_element_api_modifyvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,modifying,modify,change,changing,edit,editing,modifyvolumes 
summary: 您可以使用ModifyVolumes方法一次設定多達500個現有磁碟區。變更會立即生效。如果ModifyVolumes無法修改任何指定的磁碟區、則不會變更任何指定的磁碟區。 
---
= ModifyVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「磁碟區」方法一次設定多達500個現有磁碟區。變更會立即生效。如果「多個磁碟區」無法修改任何指定的磁碟區、則不會變更任何指定的磁碟區。

如果您在修改磁碟區時未指定QoS值、則每個磁碟區的QoS值將維持不變。您可以執行「GetDefaultQoS」方法來擷取新建立磁碟區的預設QoS值。

當您需要增加要複寫的磁碟區大小時、請依照下列順序執行此動作、以避免發生複寫錯誤：

. 利用「複製目標」存取來增加磁碟區的大小。
. 利用讀寫存取權來增加來源或磁碟區的大小。


確保目標和來源磁碟區大小相同。


NOTE: 如果您將存取狀態變更為鎖定或複製目標、則所有現有的iSCSI連線都會終止。



== 參數

此方法具有下列輸入參數：

|===
| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
存取
 a| 
允許存取磁碟區。可能值：

* 「ReadOnly」：只允許讀取作業。
* 「ReadWrite」：允許讀取和寫入。
* 「鎖定」：不允許讀取或寫入。如果未指定、存取值不會變更。
* 「重新編製目標」：將磁碟區識別為配對一組磁碟區的目標Volume。如果Volume未配對、存取狀態會鎖定。如果未指定值、則存取值不會變更。

 a| 
字串
 a| 
無
 a| 
否



 a| 
帳戶ID
 a| 
重新指派磁碟區的AccountID。如果未指定、則會使用先前的帳戶名稱。
 a| 
整數
 a| 
無
 a| 
否



 a| 
AssociatedWithQoSPolicy
 a| 
將磁碟區與指定的QoS原則建立關聯。可能值：

* 「true」：將磁碟區與QoSPolicyID參數中指定的QoS原則建立關聯。
* 「假」：請勿將磁碟區與QoSPolicyID參數中指定的QoS原則建立關聯。如果為假、則會移除任何現有的原則關聯、無論您是否在QoSPolicy參數中指定QoS原則。

 a| 
布林值
 a| 
無
 a| 
否



 a| 
屬性
 a| 
Json物件格式的名稱-值配對清單。
 a| 
Json物件
 a| 
無
 a| 
否



 a| 
CREATETIM
 a| 
ISO 8601日期字串、設定為新的Volume建立日期。如果設定為true、則為必要。
 a| 
ISO 8601字串
 a| 
無
 a| 
否



 a| 
dontMoveforIopsRebalance
 a| 
防止磁碟區在負載平衡與實際 IOPS 時移動。此設定從元素 12.8 開始提供，只有在啟用時才有效link:reference_element_api_enablefeature.html["Volume LoadBalanceOnActualIOPS"]。可能值：

* `true`： Volume 不會根據實際 IOPS 來平衡負載。
* `false`： Volume 會根據實際的 IOPS 來平衡負載。


* 注意 * ：高可用度（節點故障）的平衡優先於 `VolumeLoadBalanceOnActualIOPS`和 `dontMoveforIopsRebalance`。
| 布林值 | 錯 | 否 


 a| 
已啓用SnapMirrorReplication
 a| 
決定磁碟區是否可用於SnapMirror端點的複寫。可能值：

* "真的"
* 「假」

 a| 
布林值
 a| 
錯
 a| 
否



| 五分大小 | 指定Volume支援的先進先出（FIFO）快照數量上限。請注意、FIFO和非FIFO快照都使用同一個磁碟區上可用的快照插槽集區。使用此選項可限制可用快照插槽的FIFO快照使用量。請注意、您無法將此值修改為小於目前的FIFO快照計數。 | 整數 | 無 | 否 


| 最小大小 | 指定僅保留給先進先出（FIFO）快照的快照插槽數。由於FIFO和非FIFO快照共用相同的資源池、因此minFifoSizer參數會將可能的非FIFO快照總數減少相同數量。請注意、您無法修改此值、使其與目前的非FIFO快照計數發生衝突。 | 整數 | 無 | 否 


 a| 
模式
 a| 
Volume複寫模式。可能值：

* 「asynch」：等待系統確認資料儲存在來源、然後再寫入目標。
* 「Sync」：不需等待來源的資料傳輸確認、即可開始將資料寫入目標。

 a| 
字串
 a| 
無
 a| 
否



 a| 
QoS
 a| 
磁碟區的新服務品質設定。如果未指定、則不會變更QoS設定。可能值：

* 《IOPS》
* 《MaxIOPS》
* 《burstIOPS》

 a| 
xref:reference_element_api_qos.adoc[QoS]
 a| 
無
 a| 
否



 a| 
qosPolicyID
 a| 
應將QoS設定套用至指定磁碟區的原則ID。此參數與QoS參數互不相容。
 a| 
整數
 a| 
無
 a| 
否



 a| 
設定建立時間
 a| 
設為true可變更磁碟區建立的記錄日期。
 a| 
布林值
 a| 
無
 a| 
否



 a| 
累計大小
 a| 
磁碟區的新大小（以位元組為單位）。1000000000等於1GB。大小會四捨五入至最接近的MB大小。此參數只能用於增加磁碟區的大小。
 a| 
整數
 a| 
無
 a| 
否



 a| 
Volume ID
 a| 
要修改之磁碟區的磁碟區ID清單。
 a| 
整數陣列
 a| 
無
 a| 
是的

|===


== 傳回值

此方法具有下列傳回值：

|===
| 名稱 | 說明 | 類型 


 a| 
Volume
 a| 
包含每個新修改磁碟區資訊的物件陣列。
 a| 
xref:reference_element_api_volume.adoc[Volume] 陣列

|===


== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
  "method": "ModifyVolumes",
  "params": {
    "volumeIDs": [319,22],
    "access": "readWrite",
    "dontMoveForIopsRebalance": false
  },
  "id": 1
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
    "volumes":
      {
        "access":  "readWrite,
        "accountID": 22,
        "attributes": {},
        "blockSize": 4096,
        "createTime": "2024-04-01T19:39:40Z",
        "currentProtectionScheme": "doubleHelix",
        "deleteTime": "",
        "dontMoveForIopsRebalance": false,
        "enable512e": false,
        "enableSnapMirrorReplication": false,
        "fifoSize": 24,
        "iqn": "iqn.2010-01.com.solidfire:3eeu.suite40.319",
        "lastAccessTime": "2024-04-02T12:41:34Z",
        "lastAccessTimeIO": "2024-04-01T20:41:19Z",
        "minFifoSize": 0,
        "name": "suite40",
        "previousProtectionScheme": null,
        "purgeTime": "",
        "qos": {
          "burstIOPS": 27000,
          "burstTime": 60,
          "curve": {
            "1048576": 15000,
            "131072": 1950,
            "16384": 270,
            "262144": 3900,
            "32768": 500,
            "4096": 100,
            "524288": 7600,
            "65536": 1000,
            "8192": 160
          },
          "maxIOPS": 27000,
          "minIOPS": 500
        },
        "qosPolicyID": null,
        "scsiEUIDeviceID": "336565750000013ff47acc0100000000",
        "scsiNAADeviceID": "6f47acc100000000336565750000013f",
        "sliceCount": 1,
        "status": "active",
        "totalSize": 1000000716800,
        "virtualVolumeID": null,
        "volumeAccessGroups": [
        22
        ],
        "volumeConsistencyGroupUUID": "3003109e-6e75-444c-8cee-470d641a09c3",
        "volumeID": 319,
        "volumePairs": [],
        "
      }
  }
}
----


== 新的自版本

9.6



== 如需詳細資訊、請參閱

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
