---
permalink: api/reference_element_api_initiator.html 
sidebar: sidebar 
keywords: object,objects,initiator 
summary: 啟動器物件包含iSCSI或Fibre Channel啟動器的相關資訊。啟動器物件可以包含IQN或WWPN識別碼。您可以使用清單啟動器方法取得系統上已知的所有啟動器清單。您可以使用啟動器物件、透過磁碟區存取群組來設定SCSI啟動器對一組磁碟區的存取權。啟動器一次只能是一個Volume存取群組的成員。您可以使用「建立啟動器」和「修改啟動器」方法、指定一或多個虛擬網路ID、以限制啟動器存取一或多個VLAN。如果您未指定任何虛擬網路、啟動器就可以存取所有網路。 
---
= 啟動器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
啟動器物件包含iSCSI或Fibre Channel啟動器的相關資訊。啟動器物件可以包含IQN或WWPN識別碼。您可以使用「清單啟動器」方法取得系統上已知的所有啟動器清單。您可以使用啟動器物件、透過磁碟區存取群組來設定SCSI啟動器對一組磁碟區的存取權。啟動器一次只能是一個Volume存取群組的成員。您可以使用「建立啟動器」和「多個啟動器」方法來指定一或多個虛擬網路ID、以限制啟動器存取一或多個VLAN。如果未指定任何虛擬網路、啟動器就可以存取所有網路。



== 物件成員

此物件包含下列成員：

|===
| 名稱 | 說明 | 類型 


 a| 
別名
 a| 
指派給啟動器的易記名稱（如果有）。
 a| 
字串



 a| 
屬性
 a| 
指派給此啟動器的一組Json屬性。如果未指派任何屬性、則為空白。
 a| 
Json物件



 a| 
chap使用 者名稱
 a| 
此啟動器的唯一CHAP使用者名稱。
 a| 
字串



 a| 
初始化者ID
 a| 
啟動器的數字識別碼。
 a| 
整數



 a| 
初始器名稱
 a| 
啟動器名稱（IQN或WWPN格式）。
 a| 
字串



 a| 
初始化者機密
 a| 
用於驗證啟動器的CHAP機密。
 a| 
字串



 a| 
必要功能
 a| 
如果此啟動器需要CHAP、則為true。
 a| 
布林值



 a| 
目標機密
 a| 
用於驗證目標的CHAP機密（使用交互CHAP驗證時）。
 a| 
字串



 a| 
虛擬化網路ID
 a| 
與此啟動器相關聯的虛擬網路識別碼清單。如果定義了一個或多個、此啟動器將只能登入指定的虛擬網路。如果未定義任何虛擬網路、此啟動器就能登入所有網路。
 a| 
整數



 a| 
Volume存取群組
 a| 
此啟動器所屬的Volume存取群組ID清單。
 a| 
整數陣列

|===


== 如需詳細資訊、請參閱

xref:reference_element_api_listinitiators.adoc[清單啟動器]
