---
permalink: api/reference_element_api_copyvolume.html 
sidebar: sidebar 
keywords: volume,volumes,CopyVolume,overwrite,overwriting,data 
summary: 您可以使用CopyVolume方法、將現有磁碟區的資料內容覆寫為另一個磁碟區（或快照）的資料內容。目的地Volume的屬性（例如IQN、QoS設定、大小、帳戶和Volume存取群組成員資格）不會變更。目的地Volume必須已經存在、而且必須與來源Volume大小相同。 
---
= CopyVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「CopyVolume」（複本磁碟區）方法、以其他磁碟區（或快照）的資料內容覆寫現有磁碟區的資料內容。目的地Volume的屬性（例如IQN、QoS設定、大小、帳戶和Volume存取群組成員資格）不會變更。目的地Volume必須已經存在、而且必須與來源Volume大小相同。

最好是用戶端在作業開始之前卸載目的地Volume。如果在作業期間修改目的地Volume、變更將會遺失。此作業可能需要多長時間才能完成。您可以使用 xref:reference_element_api_getasyncresult.adoc[Get非 同步結果] 判斷程序何時完成的方法、以及 xref:reference_element_api_listsyncjobs.adoc[listSyncJobs] 以查看複本的進度。



== 參數

此方法具有下列輸入參數：

|===
| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
dstVolume ID
 a| 
要覆寫之磁碟區的Volume ID。
 a| 
整數
 a| 
無
 a| 
是的



 a| 
Volume ID
 a| 
要讀取之磁碟區的Volume ID。
 a| 
整數
 a| 
無
 a| 
是的



 a| 
Snapshot ID
 a| 
作為實體複本來源的快照ID。如果未提供ID、則會使用目前作用中的Volume。
 a| 
整數
 a| 
無
 a| 
否

|===


== 傳回值

此方法具有下列傳回值：

|===


| 名稱 | 說明 | 類型 


 a| 
asyncdle
 a| 
處理用於獲取操作結果的值。
 a| 
整數



 a| 
cloneID
 a| 
新複製Volume的CloneID。
 a| 
整數

|===


== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
   "method": "CopyVolume",
   "params": {
      "volumeID" : 3,
      "dstVolumeID" : 2
   },
   "id" : 1
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
    "asyncHandle": 9,
    "cloneID": 5
  }
}
----


== 新的自版本

9.6



== 如需詳細資訊、請參閱

* xref:reference_element_api_getasyncresult.adoc[Get非 同步結果]
* xref:reference_element_api_listsyncjobs.adoc[listSyncJobs]

