---
permalink: api/reference_element_api_enablemaintenancemode.html 
sidebar: sidebar 
keywords: maintenance,enable,mode 
summary: 您可以使用啟用維護模式方法來準備儲存節點以進行維護。維護案例包括任何需要關閉或重新啟動節點的工作。 
---
= 啟用維護模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「啟用維護模式」方法來準備儲存節點以進行維護。維護案例包括任何需要關閉或重新啟動節點的工作。



== 參數

此方法具有下列輸入參數：

|===
| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
forceWithUnresolvedFaults
 a| 
即使存在封鎖叢集故障、仍會強制啟用此節點的維護模式。
 a| 
布林值
 a| 
錯
 a| 
否



 a| 
節點
 a| 
要置於維護模式的節點ID清單。一次只支援一個節點。
 a| 
整數陣列
 a| 
無
 a| 
是的



 a| 
PerMinutePrimarySwapLimit
 a| 
每分鐘交換的主要切片數。如果未指定、則會一次交換所有主要切片。
 a| 
整數
 a| 
無
 a| 
否



 a| 
逾時
 a| 
指定在自動停用維護模式之前、應保持啟用的時間長度。格式化為時間字串（例如、hh：mm：sss）。如果未指定、維護模式將維持啟用、直到明確停用為止。
 a| 
字串
 a| 
無
 a| 
否

|===


== 傳回值

此方法具有下列傳回值：

|===


| 名稱 | 說明 | 類型 


 a| 
asyncdle
 a| 
您可以使用Getynprynet方法擷取此asyncdyle、並判斷維護模式轉換何時完成。
 a| 
整數



 a| 
目前模式
 a| 
節點目前的維護模式狀態。可能值：

* 停用：未要求維護。
* 容錯移轉：節點無法從維護模式中恢復。
* RecoveringFromMaintenance：節點正在從維護模式中恢復。
* 準備維護：正在採取行動、準備節點執行維護作業。
* ReadyForMaintenance：節點已準備好進行維護。

 a| 
維護模式（字串）



 a| 
申請模式
 a| 
節點要求的維護模式狀態。可能值：

* 停用：未要求維護。
* 容錯移轉：節點無法從維護模式中恢復。
* RecoveringFromMaintenance：節點正在從維護模式中恢復。
* 準備維護：正在採取行動、準備節點執行維護作業。
* ReadyForMaintenance：節點已準備好進行維護。

 a| 
維護模式（字串）

|===


== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
  "method": "EnableMaintenanceMode",
  "params": {
    "forceWithUnresolvedFaults": False,
    "nodes": [6],
    "perMinutePrimarySwapLimit" : 40,
    "timeout" : "01:00:05"
  },
"id": 1
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "ReadyForMaintenance",
        "asyncHandle": 1,
        "currentMode": "Disabled"
    }
}
----


== 新的自版本

12.2



== 如需詳細資訊、請參閱

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["儲存維護模式概念NetApp HCI"^]
