---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: 您可以使用SetSnmpInfo方法、在叢集節點上設定SNMP版本2和版本3。您使用此介面設定的值會套用至叢集中的所有節點、而傳遞的值會取代先前任何呼叫中設定的所有值給SetSnmpInfo。 
---
= SetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「etSnmpInfo」方法、在叢集節點上設定SNMP版本2和版本3。您使用此介面設定的值會套用至叢集中的所有節點、而傳遞的值會取代任何先前呼叫中設定的所有值「etSnmpInfo」。



== 參數


NOTE: SetSnmpInfo不適用於Element 6.0及更新版本。使用 xref:reference_element_api_enablesnmp.adoc[啟用Snmp] 和 xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] 方法。

此方法具有下列輸入參數：

|===
| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
網路
 a| 
網路清單、以及網路對叢集節點上執行的SNMP伺服器有何存取類型。請參閱SNMP xref:reference_element_api_network_snmp.adoc[網路] 可能值的物件。此參數僅適用於SNMP v2。
 a| 
xref:reference_element_api_network_snmp.adoc[網路] 陣列
 a| 
無
 a| 
否



 a| 
已啟用
 a| 
如果設為true、則會在叢集中的每個節點上啟用SNMP。
 a| 
布林值
 a| 
錯
 a| 
否



 a| 
已啟用snmpV3
 a| 
如果設為true、則會在叢集中的每個節點上啟用SNMP v3。
 a| 
布林值
 a| 
錯
 a| 
否



 a| 
使用者
 a| 
如果已啟用SNMP v3、則必須傳遞此值來取代networks參數。此參數僅適用於SNMP v3。
 a| 
xref:reference_element_api_usmuser.adoc[使用者]
 a| 
無
 a| 
否

|===


== 傳回值

此方法沒有傳回值。



== 啟用SNMP v3的申請範例

此方法的要求類似於下列範例：

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== 啟用SNMP v2的申請範例

此方法的要求類似於下列範例：

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== 新的自版本

9.6
