---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: 您可以使用ModifyVirtualNetwork方法來變更現有虛擬網路的屬性。 
---
= ModifyVirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「共享虛擬網路」方法來變更現有虛擬網路的屬性。

此方法可讓您新增或移除位址區塊、變更網路遮罩、或修改虛擬網路的名稱或說明。您也可以使用它來啟用或停用命名空間、以及在虛擬網路上啟用命名空間時新增或移除閘道。


NOTE: 此方法需要虛擬網路ID或虛擬網路標籤做為參數、但不能同時做為參數。

注意：

變更命名空間參數、為現有虛擬網路啟用或停用可路由的儲存VLAN功能、會中斷虛擬網路處理的任何流量。最好是在排程的維護期間變更命名空間參數。



== 參數

此方法具有下列輸入參數：

|===


| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
虛擬網路ID
 a| 
要修改之虛擬網路的唯一識別碼。這是叢集指派的虛擬網路ID。
 a| 
整數
 a| 
無
 a| 
否



 a| 
虛擬化網路標籤
 a| 
識別要修改之虛擬網路的網路標籤。
 a| 
整數
 a| 
無
 a| 
否



 a| 
定址鎖定
 a| 
為此虛擬網路設定的新位址區塊。這可能包括新的位址區塊、以新增至現有物件、或省略需要移除的未使用位址區塊。或者、您也可以擴充或縮小現有位址區塊的大小。您只能增加虛擬網路物件的起始定址鎖定大小、永遠無法減少。此物件的必要成員：

* Start（開始）：IP位址範圍的開頭。（字串）
* 大小：要包含在區塊中的IP位址數目。（整數）

 a| 
Json物件
 a| 
無
 a| 
否



 a| 
閘道
 a| 
虛擬網路閘道的IP位址。此參數僅在命名空間參數設定為true時有效。
 a| 
字串
 a| 
無
 a| 
否



 a| 
屬性
 a| 
Json物件格式的名稱-值配對清單。
 a| 
Json物件
 a| 
無
 a| 
否



 a| 
名稱
 a| 
虛擬網路的新名稱。
 a| 
字串
 a| 
無
 a| 
否



 a| 
命名空間
 a| 
設為true時、可重新建立虛擬網路並設定命名空間以容納該虛擬網路、藉此啟用可路由的儲存VLAN功能。設為假時、會停用虛擬網路的VRF功能。變更此值會中斷流經此虛擬網路的流量。
 a| 
布林值
 a| 
無
 a| 
否



 a| 
網路遮罩
 a| 
此虛擬網路的新網路遮罩。
 a| 
字串
 a| 
無
 a| 
否



 a| 
服務
 a| 
此虛擬網路的儲存虛擬IP位址。無法變更虛擬網路的SVIP。您必須建立新的虛擬網路、才能使用不同的SVIP位址。
 a| 
字串
 a| 
無
 a| 
否

|===


== 傳回值

此方法沒有傳回值。



== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== 新的自版本

9.6
